---@type {[string]:string}
return { ["minecraft:yellow_banner"] = "Yellow Banner", ["minecraft:warped_planks"] = "Warped Planks",
  ["minecraft:tube_coral"] = "Tube Coral", ["minecraft:purple_concrete"] = "Purple Concrete",
  ["minecraft:potted_lily_of_the_valley"] = "Potted Lily of the Valley",
  ["minecraft:yellow_candle_cake"] = "Cake with Yellow Candle", ["minecraft:diorite"] = "Diorite",
  ["minecraft:bamboo_block"] = "Block of Bamboo", ["minecraft:birch_trapdoor"] = "Birch Trapdoor",
  ["minecraft:seagrass"] = "Seagrass", ["minecraft:pink_bed"] = "Pink Bed", ["minecraft:gray_banner"] = "Gray Banner",
  ["minecraft:white_carpet"] = "White Carpet", ["minecraft:anvil"] = "Anvil",
  ["minecraft:infested_mossy_stone_bricks"] = "Infested Mossy Stone Bricks",
  ["minecraft:warped_trapdoor"] = "Warped Trapdoor", ["minecraft:fire_coral_wall_fan"] = "Fire Coral Wall Fan",
  ["minecraft:nether_wart_block"] = "Nether Wart Block", ["minecraft:potted_warped_roots"] = "Potted Warped Roots",
  ["minecraft:mossy_cobblestone_stairs"] = "Mossy Cobblestone Stairs", ["minecraft:purple_carpet"] = "Purple Carpet",
  ["minecraft:emerald_block"] = "Block of Emerald", ["minecraft:beacon"] = "Beacon",
  ["minecraft:chiseled_bookshelf"] = "Chiseled Bookshelf", ["minecraft:crimson_roots"] = "Crimson Roots",
  ["minecraft:cobblestone_slab"] = "Cobblestone Slab", ["minecraft:piglin_wall_head"] = "Piglin Wall Head",
  ["minecraft:jukebox"] = "Jukebox", ["minecraft:potted_pink_tulip"] = "Potted Pink Tulip",
  ["minecraft:lime_wool"] = "Lime Wool", ["minecraft:glow_lichen"] = "Glow Lichen",
  ["minecraft:raw_gold_block"] = "Block of Raw Gold", ["minecraft:chain_command_block"] = "Chain Command Block",
  ["minecraft:sandstone_wall"] = "Sandstone Wall", ["minecraft:nether_brick_wall"] = "Nether Brick Wall",
  ["minecraft:lime_stained_glass_pane"] = "Lime Stained Glass Pane", ["minecraft:skeleton_skull"] = "Skeleton Skull",
  ["minecraft:jigsaw"] = "Jigsaw Block", ["minecraft:orange_candle_cake"] = "Cake with Orange Candle",
  ["minecraft:stripped_jungle_wood"] = "Stripped Jungle Wood", ["minecraft:coal_ore"] = "Coal Ore",
  ["minecraft:green_glazed_terracotta"] = "Green Glazed Terracotta", ["minecraft:dandelion"] = "Dandelion",
  ["minecraft:jungle_wood"] = "Jungle Wood", ["minecraft:fire"] = "Fire", ["minecraft:water_cauldron"] = "Water Cauldron",
  ["minecraft:spruce_wall_hanging_sign"] = "Spruce Wall Hanging Sign", ["minecraft:lime_candle"] = "Lime Candle",
  ["minecraft:dark_prismarine_stairs"] = "Dark Prismarine Stairs", ["minecraft:oak_sign"] = "Oak Sign",
  ["minecraft:light_blue_glazed_terracotta"] = "Light Blue Glazed Terracotta",
  ["minecraft:deepslate_diamond_ore"] = "Deepslate Diamond Ore", ["minecraft:orange_banner"] = "Orange Banner",
  ["minecraft:fern"] = "Fern", ["minecraft:respawn_anchor"] = "Respawn Anchor", ["minecraft:torch"] = "Torch",
  ["minecraft:redstone_ore"] = "Redstone Ore", ["minecraft:copper_ore"] = "Copper Ore",
  ["minecraft:end_stone_brick_slab"] = "End Stone Brick Slab", ["minecraft:green_carpet"] = "Green Carpet",
  ["minecraft:sea_lantern"] = "Sea Lantern", ["minecraft:bell"] = "Bell", ["minecraft:sandstone"] = "Sandstone",
  ["minecraft:warped_wall_sign"] = "Warped Wall Sign", ["minecraft:soul_wall_torch"] = "Soul Wall Torch",
  ["minecraft:stripped_oak_log"] = "Stripped Oak Log", ["minecraft:beetroots"] = "Beetroots",
  ["minecraft:yellow_concrete_powder"] = "Yellow Concrete Powder", ["minecraft:potted_dandelion"] = "Potted Dandelion",
  ["minecraft:orange_candle"] = "Orange Candle", ["minecraft:polished_diorite"] = "Polished Diorite",
  ["minecraft:purple_glazed_terracotta"] = "Purple Glazed Terracotta", ["minecraft:spruce_sapling"] = "Spruce Sapling",
  ["minecraft:smooth_stone"] = "Smooth Stone", ["minecraft:soul_torch"] = "Soul Torch",
  ["minecraft:gray_concrete_powder"] = "Gray Concrete Powder", ["minecraft:black_terracotta"] = "Black Terracotta",
  ["minecraft:structure_void"] = "Structure Void", ["minecraft:iron_trapdoor"] = "Iron Trapdoor",
  ["minecraft:glass"] = "Glass", ["minecraft:red_candle_cake"] = "Cake with Red Candle", ["minecraft:cobweb"] = "Cobweb",
  ["minecraft:light_blue_banner"] = "Light Blue Banner", ["minecraft:rose_bush"] = "Rose Bush",
  ["minecraft:sculk_vein"] = "Sculk Vein", ["minecraft:polished_andesite_slab"] = "Polished Andesite Slab",
  ["minecraft:dead_horn_coral_wall_fan"] = "Dead Horn Coral Wall Fan",
  ["minecraft:crimson_wall_hanging_sign"] = "Crimson Wall Hanging Sign", ["minecraft:granite_wall"] = "Granite Wall",
  ["minecraft:deepslate_copper_ore"] = "Deepslate Copper Ore", ["minecraft:gilded_blackstone"] = "Gilded Blackstone",
  ["minecraft:warped_fence"] = "Warped Fence", ["minecraft:acacia_sign"] = "Acacia Sign",
  ["minecraft:white_tulip"] = "White Tulip", ["minecraft:cracked_nether_bricks"] = "Cracked Nether Bricks",
  ["minecraft:brick_wall"] = "Brick Wall", ["minecraft:cut_red_sandstone"] = "Cut Red Sandstone",
  ["minecraft:chest"] = "Chest", ["minecraft:dark_oak_wood"] = "Dark Oak Wood",
  ["minecraft:spruce_fence"] = "Spruce Fence",
  ["minecraft:dripstone_block"] = "Dripstone Block", ["minecraft:gray_shulker_box"] = "Gray Shulker Box",
  ["minecraft:brown_concrete"] = "Brown Concrete",
  ["minecraft:waxed_exposed_cut_copper_stairs"] = "Waxed Exposed Cut Copper Stairs",
  ["minecraft:polished_blackstone_stairs"] = "Polished Blackstone Stairs",
  ["minecraft:brown_mushroom"] = "Brown Mushroom",
  ["minecraft:white_terracotta"] = "White Terracotta", ["minecraft:red_sandstone_slab"] = "Red Sandstone Slab",
  ["minecraft:fire_coral"] = "Fire Coral", ["minecraft:frogspawn"] = "Frogspawn",
  ["minecraft:mangrove_slab"] = "Mangrove Slab", ["minecraft:cyan_glazed_terracotta"] = "Cyan Glazed Terracotta",
  ["minecraft:target"] = "Target", ["minecraft:gray_glazed_terracotta"] = "Gray Glazed Terracotta",
  ["minecraft:sweet_berry_bush"] = "Sweet Berry Bush",
  ["minecraft:dead_bubble_coral_wall_fan"] = "Dead Bubble Coral Wall Fan",
  ["minecraft:stripped_dark_oak_log"] = "Stripped Dark Oak Log", ["minecraft:rail"] = "Rail",
  ["minecraft:raw_iron_block"] = "Block of Raw Iron", ["minecraft:attached_melon_stem"] = "Attached Melon Stem",
  ["minecraft:acacia_pressure_plate"] = "Acacia Pressure Plate", ["minecraft:spruce_log"] = "Spruce Log",
  ["minecraft:oxidized_cut_copper"] = "Oxidized Cut Copper", ["minecraft:iron_door"] = "Iron Door",
  ["minecraft:smooth_quartz"] = "Smooth Quartz Block",
  ["minecraft:waxed_oxidized_cut_copper_stairs"] = "Waxed Oxidized Cut Copper Stairs",
  ["minecraft:black_stained_glass_pane"] = "Black Stained Glass Pane", ["minecraft:oak_stairs"] = "Oak Stairs",
  ["minecraft:acacia_wall_sign"] = "Acacia Wall Sign", ["minecraft:end_stone_bricks"] = "End Stone Bricks",
  ["minecraft:bubble_coral_block"] = "Bubble Coral Block", ["minecraft:candle"] = "Candle",
  ["minecraft:red_sandstone"] = "Red Sandstone", ["minecraft:sculk_shrieker"] = "Sculk Shrieker",
  ["minecraft:end_gateway"] = "End Gateway", ["minecraft:spruce_door"] = "Spruce Door",
  ["minecraft:red_concrete_powder"] = "Red Concrete Powder",
  ["minecraft:blue_stained_glass_pane"] = "Blue Stained Glass Pane",
  ["minecraft:polished_blackstone"] = "Polished Blackstone", ["minecraft:comparator"] = "Redstone Comparator",
  ["minecraft:blue_concrete"] = "Blue Concrete", ["minecraft:pink_banner"] = "Pink Banner",
  ["minecraft:cyan_concrete"] = "Cyan Concrete", ["minecraft:brown_stained_glass_pane"] = "Brown Stained Glass Pane",
  ["minecraft:green_shulker_box"] = "Green Shulker Box", ["minecraft:brown_wool"] = "Brown Wool",
  ["minecraft:peony"] = "Peony", ["minecraft:flower_pot"] = "Flower Pot",
  ["minecraft:infested_stone_bricks"] = "Infested Stone Bricks",
  ["minecraft:crimson_hanging_sign"] = "Crimson Hanging Sign", ["minecraft:bookshelf"] = "Bookshelf",
  ["minecraft:muddy_mangrove_roots"] = "Muddy Mangrove Roots", ["minecraft:bricks"] = "Bricks",
  ["minecraft:oxidized_copper"] = "Oxidized Copper", ["minecraft:mangrove_pressure_plate"] = "Mangrove Pressure Plate",
  ["minecraft:chiseled_quartz_block"] = "Chiseled Quartz Block", ["minecraft:end_stone"] = "End Stone",
  ["minecraft:chorus_plant"] = "Chorus Plant", ["minecraft:bamboo_pressure_plate"] = "Bamboo Pressure Plate",
  ["minecraft:smooth_sandstone_slab"] = "Smooth Sandstone Slab",
  ["minecraft:infested_chiseled_stone_bricks"] = "Infested Chiseled Stone Bricks",
  ["minecraft:acacia_door"] = "Acacia Door", ["minecraft:blue_concrete_powder"] = "Blue Concrete Powder",
  ["minecraft:gray_stained_glass"] = "Gray Stained Glass", ["minecraft:andesite_wall"] = "Andesite Wall",
  ["minecraft:dead_horn_coral"] = "Dead Horn Coral", ["minecraft:verdant_froglight"] = "Verdant Froglight",
  ["minecraft:dragon_wall_head"] = "Dragon Wall Head", ["minecraft:dirt"] = "Dirt",
  ["minecraft:mangrove_sign"] = "Mangrove Sign", ["minecraft:lime_concrete_powder"] = "Lime Concrete Powder",
  ["minecraft:cut_sandstone"] = "Cut Sandstone", ["minecraft:tuff"] = "Tuff", ["minecraft:player_head"] = "Player Head",
  ["minecraft:andesite_stairs"] = "Andesite Stairs", ["minecraft:dragon_egg"] = "Dragon Egg",
  ["minecraft:quartz_slab"] = "Quartz Slab", ["minecraft:polished_andesite"] = "Polished Andesite",
  ["minecraft:jungle_planks"] = "Jungle Planks", ["minecraft:red_glazed_terracotta"] = "Red Glazed Terracotta",
  ["minecraft:acacia_trapdoor"] = "Acacia Trapdoor", ["minecraft:light_gray_wool"] = "Light Gray Wool",
  ["minecraft:spruce_slab"] = "Spruce Slab", ["minecraft:bamboo_fence_gate"] = "Bamboo Fence Gate",
  ["minecraft:cobbled_deepslate_wall"] = "Cobbled Deepslate Wall",
  ["minecraft:magenta_glazed_terracotta"] = "Magenta Glazed Terracotta", ["minecraft:nether_portal"] = "Nether Portal",
  ["minecraft:pink_tulip"] = "Pink Tulip", ["minecraft:ancient_debris"] = "Ancient Debris",
  ["minecraft:bamboo"] = "Bamboo",
  ["minecraft:bamboo_sapling"] = "Bamboo Shoot", ["minecraft:activator_rail"] = "Activator Rail",
  ["minecraft:blue_orchid"] = "Blue Orchid", ["minecraft:jungle_fence_gate"] = "Jungle Fence Gate",
  ["minecraft:black_concrete"] = "Black Concrete", ["minecraft:carrots"] = "Carrots",
  ["minecraft:brain_coral_fan"] = "Brain Coral Fan", ["minecraft:white_candle_cake"] = "Cake with White Candle",
  ["minecraft:chiseled_red_sandstone"] = "Chiseled Red Sandstone", ["minecraft:blue_banner"] = "Blue Banner",
  ["minecraft:smooth_quartz_slab"] = "Smooth Quartz Slab", ["minecraft:weathered_cut_copper"] = "Weathered Cut Copper",
  ["minecraft:end_stone_brick_stairs"] = "End Stone Brick Stairs", ["minecraft:creeper_head"] = "Creeper Head",
  ["minecraft:orange_carpet"] = "Orange Carpet", ["minecraft:enchanting_table"] = "Enchanting Table",
  ["minecraft:moss_carpet"] = "Moss Carpet", ["minecraft:petrified_oak_slab"] = "Petrified Oak Slab",
  ["minecraft:yellow_bed"] = "Yellow Bed", ["minecraft:lime_shulker_box"] = "Lime Shulker Box",
  ["minecraft:waxed_exposed_cut_copper_slab"] = "Waxed Exposed Cut Copper Slab",
  ["minecraft:polished_granite_slab"] = "Polished Granite Slab", ["minecraft:lime_candle_cake"] = "Cake with Lime Candle",
  ["minecraft:magenta_candle"] = "Magenta Candle", ["minecraft:light_gray_banner"] = "Light Gray Banner",
  ["minecraft:magenta_concrete"] = "Magenta Concrete", ["minecraft:lectern"] = "Lectern",
  ["minecraft:mud_bricks"] = "Mud Bricks", ["minecraft:lapis_block"] = "Block of Lapis Lazuli",
  ["minecraft:cyan_banner"] = "Cyan Banner", ["minecraft:mangrove_roots"] = "Mangrove Roots",
  ["minecraft:cracked_deepslate_tiles"] = "Cracked Deepslate Tiles",
  ["minecraft:polished_deepslate_slab"] = "Polished Deepslate Slab",
  ["minecraft:deepslate_brick_stairs"] = "Deepslate Brick Stairs",
  ["minecraft:deepslate_coal_ore"] = "Deepslate Coal Ore",
  ["minecraft:magenta_stained_glass_pane"] = "Magenta Stained Glass Pane",
  ["minecraft:granite_stairs"] = "Granite Stairs",
  ["minecraft:bamboo_planks"] = "Bamboo Planks", ["minecraft:light_blue_bed"] = "Light Blue Bed",
  ["minecraft:pumpkin"] = "Pumpkin", ["minecraft:light_gray_shulker_box"] = "Light Gray Shulker Box",
  ["minecraft:white_banner"] = "White Banner", ["minecraft:chiseled_sandstone"] = "Chiseled Sandstone",
  ["minecraft:cyan_candle_cake"] = "Cake with Cyan Candle", ["minecraft:frosted_ice"] = "Frosted Ice",
  ["minecraft:deepslate_brick_slab"] = "Deepslate Brick Slab", ["minecraft:crimson_button"] = "Crimson Button",
  ["minecraft:mossy_stone_brick_wall"] = "Mossy Stone Brick Wall", ["minecraft:campfire"] = "Campfire",
  ["minecraft:light_gray_terracotta"] = "Light Gray Terracotta",
  ["minecraft:deepslate_brick_wall"] = "Deepslate Brick Wall", ["minecraft:oak_wood"] = "Oak Wood",
  ["minecraft:black_concrete_powder"] = "Black Concrete Powder", ["minecraft:zombie_wall_head"] = "Zombie Wall Head",
  ["minecraft:black_bed"] = "Black Bed", ["minecraft:mangrove_wall_hanging_sign"] = "Mangrove Wall Hanging Sign",
  ["minecraft:tall_grass"] = "Tall Grass", ["minecraft:note_block"] = "Note Block",
  ["minecraft:brown_glazed_terracotta"] = "Brown Glazed Terracotta", ["minecraft:waxed_cut_copper"] = "Waxed Cut Copper",
  ["minecraft:potted_dead_bush"] = "Potted Dead Bush",
  ["minecraft:jungle_wall_hanging_sign"] = "Jungle Wall Hanging Sign",
  ["minecraft:polished_blackstone_bricks"] = "Polished Blackstone Bricks",
  ["minecraft:black_candle_cake"] = "Cake with Black Candle", ["minecraft:deepslate_tiles"] = "Deepslate Tiles",
  ["minecraft:fire_coral_fan"] = "Fire Coral Fan", ["minecraft:deepslate_gold_ore"] = "Deepslate Gold Ore",
  ["minecraft:potted_fern"] = "Potted Fern", ["minecraft:deepslate_iron_ore"] = "Deepslate Iron Ore",
  ["minecraft:snow"] = "Snow", ["minecraft:red_mushroom"] = "Red Mushroom",
  ["minecraft:stone_pressure_plate"] = "Stone Pressure Plate", ["minecraft:stone_brick_slab"] = "Stone Brick Slab",
  ["minecraft:birch_leaves"] = "Birch Leaves",
  ["minecraft:waxed_weathered_cut_copper_stairs"] = "Waxed Weathered Cut Copper Stairs",
  ["minecraft:dragon_head"] = "Dragon Head", ["minecraft:dark_oak_pressure_plate"] = "Dark Oak Pressure Plate",
  ["minecraft:yellow_shulker_box"] = "Yellow Shulker Box", ["minecraft:dead_tube_coral"] = "Dead Tube Coral",
  ["minecraft:lava"] = "Lava", ["minecraft:end_stone_brick_wall"] = "End Stone Brick Wall",
  ["minecraft:diamond_ore"] = "Diamond Ore", ["minecraft:stripped_dark_oak_wood"] = "Stripped Dark Oak Wood",
  ["minecraft:oak_door"] = "Oak Door", ["minecraft:waxed_cut_copper_stairs"] = "Waxed Cut Copper Stairs",
  ["minecraft:kelp_plant"] = "Kelp Plant", ["minecraft:clay"] = "Clay",
  ["minecraft:stripped_crimson_stem"] = "Stripped Crimson Stem", ["minecraft:prismarine_stairs"] = "Prismarine Stairs",
  ["minecraft:pink_shulker_box"] = "Pink Shulker Box", ["minecraft:waxed_cut_copper_slab"] = "Waxed Cut Copper Slab",
  ["minecraft:diamond_block"] = "Block of Diamond", ["minecraft:deepslate_emerald_ore"] = "Deepslate Emerald Ore",
  ["minecraft:iron_bars"] = "Iron Bars", ["minecraft:orange_stained_glass_pane"] = "Orange Stained Glass Pane",
  ["minecraft:brown_candle"] = "Brown Candle", ["minecraft:spawner"] = "Monster Spawner",
  ["minecraft:spruce_wood"] = "Spruce Wood", ["minecraft:moss_block"] = "Moss Block",
  ["minecraft:netherrack"] = "Netherrack", ["minecraft:blue_carpet"] = "Blue Carpet",
  ["minecraft:sunflower"] = "Sunflower",
  ["minecraft:gold_ore"] = "Gold Ore", ["minecraft:oak_fence"] = "Oak Fence",
  ["minecraft:red_terracotta"] = "Red Terracotta", ["minecraft:horn_coral_fan"] = "Horn Coral Fan",
  ["minecraft:black_banner"] = "Black Banner", ["minecraft:pearlescent_froglight"] = "Pearlescent Froglight",
  ["minecraft:jungle_pressure_plate"] = "Jungle Pressure Plate", ["minecraft:beehive"] = "Beehive",
  ["minecraft:large_fern"] = "Large Fern", ["minecraft:warped_roots"] = "Warped Roots",
  ["minecraft:acacia_leaves"] = "Acacia Leaves", ["minecraft:acacia_hanging_sign"] = "Acacia Hanging Sign",
  ["minecraft:dead_tube_coral_wall_fan"] = "Dead Tube Coral Wall Fan",
  ["minecraft:red_sandstone_wall"] = "Red Sandstone Wall", ["minecraft:potted_oxeye_daisy"] = "Potted Oxeye Daisy",
  ["minecraft:red_sandstone_stairs"] = "Red Sandstone Stairs", ["minecraft:black_candle"] = "Black Candle",
  ["minecraft:brown_stained_glass"] = "Brown Stained Glass", ["minecraft:chorus_flower"] = "Chorus Flower",
  ["minecraft:waxed_oxidized_copper"] = "Waxed Oxidized Copper", ["minecraft:redstone_wire"] = "Redstone Wire",
  ["minecraft:wither_rose"] = "Wither Rose", ["minecraft:light_blue_candle"] = "Light Blue Candle",
  ["minecraft:light_weighted_pressure_plate"] = "Light Weighted Pressure Plate",
  ["minecraft:magma_block"] = "Magma Block",
  ["minecraft:air"] = "Air", ["minecraft:oak_slab"] = "Oak Slab",
  ["minecraft:potted_acacia_sapling"] = "Potted Acacia Sapling", ["minecraft:light_gray_carpet"] = "Light Gray Carpet",
  ["minecraft:pink_glazed_terracotta"] = "Pink Glazed Terracotta",
  ["minecraft:smooth_quartz_stairs"] = "Smooth Quartz Stairs",
  ["minecraft:potted_mangrove_propagule"] = "Potted Mangrove Propagule",
  ["minecraft:stripped_crimson_hyphae"] = "Stripped Crimson Hyphae",
  ["minecraft:brown_shulker_box"] = "Brown Shulker Box",
  ["minecraft:smooth_sandstone_stairs"] = "Smooth Sandstone Stairs", ["minecraft:gravel"] = "Gravel",
  ["minecraft:orange_shulker_box"] = "Orange Shulker Box", ["minecraft:dark_oak_fence"] = "Dark Oak Fence",
  ["minecraft:bamboo_mosaic"] = "Bamboo Mosaic", ["minecraft:andesite"] = "Andesite",
  ["minecraft:mangrove_leaves"] = "Mangrove Leaves", ["minecraft:potted_jungle_sapling"] = "Potted Jungle Sapling",
  ["minecraft:red_nether_bricks"] = "Red Nether Bricks",
  ["minecraft:light_blue_stained_glass_pane"] = "Light Blue Stained Glass Pane",
  ["minecraft:bamboo_button"] = "Bamboo Button", ["minecraft:birch_stairs"] = "Birch Stairs",
  ["minecraft:granite"] = "Granite", ["minecraft:oxeye_daisy"] = "Oxeye Daisy",
  ["minecraft:diorite_slab"] = "Diorite Slab",
  ["minecraft:iron_block"] = "Block of Iron", ["minecraft:gray_stained_glass_pane"] = "Gray Stained Glass Pane",
  ["minecraft:purple_banner"] = "Purple Banner", ["minecraft:cracked_deepslate_bricks"] = "Cracked Deepslate Bricks",
  ["minecraft:sculk"] = "Sculk", ["minecraft:jungle_sapling"] = "Jungle Sapling",
  ["minecraft:cut_red_sandstone_slab"] = "Cut Red Sandstone Slab", ["minecraft:bamboo_door"] = "Bamboo Door",
  ["minecraft:spruce_leaves"] = "Spruce Leaves", ["minecraft:acacia_log"] = "Acacia Log",
  ["minecraft:skeleton_wall_skull"] = "Skeleton Wall Skull", ["minecraft:creeper_wall_head"] = "Creeper Wall Head",
  ["minecraft:prismarine_bricks"] = "Prismarine Bricks", ["minecraft:mossy_stone_brick_slab"] = "Mossy Stone Brick Slab",
  ["minecraft:pink_wool"] = "Pink Wool", ["minecraft:prismarine_brick_stairs"] = "Prismarine Brick Stairs",
  ["minecraft:potted_poppy"] = "Potted Poppy", ["minecraft:cyan_concrete_powder"] = "Cyan Concrete Powder",
  ["minecraft:magenta_carpet"] = "Magenta Carpet", ["minecraft:sticky_piston"] = "Sticky Piston",
  ["minecraft:coal_block"] = "Block of Coal", ["minecraft:yellow_concrete"] = "Yellow Concrete",
  ["minecraft:birch_button"] = "Birch Button", ["minecraft:mangrove_stairs"] = "Mangrove Stairs",
  ["minecraft:brown_banner"] = "Brown Banner", ["minecraft:mangrove_trapdoor"] = "Mangrove Trapdoor",
  ["minecraft:ender_chest"] = "Ender Chest", ["minecraft:lodestone"] = "Lodestone",
  ["minecraft:green_wool"] = "Green Wool",
  ["minecraft:cyan_terracotta"] = "Cyan Terracotta", ["minecraft:blackstone_wall"] = "Blackstone Wall",
  ["minecraft:cobbled_deepslate_slab"] = "Cobbled Deepslate Slab", ["minecraft:potted_allium"] = "Potted Allium",
  ["minecraft:magenta_candle_cake"] = "Cake with Magenta Candle", ["minecraft:smooth_stone_slab"] = "Smooth Stone Slab",
  ["minecraft:coarse_dirt"] = "Coarse Dirt", ["minecraft:bone_block"] = "Bone Block",
  ["minecraft:black_carpet"] = "Black Carpet", ["minecraft:stone_brick_wall"] = "Stone Brick Wall",
  ["minecraft:gold_block"] = "Block of Gold", ["minecraft:acacia_planks"] = "Acacia Planks",
  ["minecraft:stonecutter"] = "Stonecutter", ["minecraft:orange_wool"] = "Orange Wool",
  ["minecraft:oak_planks"] = "Oak Planks", ["minecraft:crimson_fence"] = "Crimson Fence",
  ["minecraft:dark_oak_door"] = "Dark Oak Door", ["minecraft:spruce_button"] = "Spruce Button",
  ["minecraft:mossy_stone_brick_stairs"] = "Mossy Stone Brick Stairs", ["minecraft:black_wool"] = "Black Wool",
  ["minecraft:dried_kelp_block"] = "Dried Kelp Block", ["minecraft:dark_oak_hanging_sign"] = "Dark Oak Hanging Sign",
  ["minecraft:mangrove_planks"] = "Mangrove Planks", ["minecraft:orange_concrete"] = "Orange Concrete",
  ["minecraft:dead_bubble_coral_block"] = "Dead Bubble Coral Block", ["minecraft:sandstone_slab"] = "Sandstone Slab",
  ["minecraft:potted_blue_orchid"] = "Potted Blue Orchid", ["minecraft:warped_button"] = "Warped Button",
  ["minecraft:crimson_door"] = "Crimson Door", ["minecraft:dark_oak_wall_hanging_sign"] = "Dark Oak Wall Hanging Sign",
  ["minecraft:stone"] = "Stone", ["minecraft:dead_brain_coral"] = "Dead Brain Coral",
  ["minecraft:pink_concrete"] = "Pink Concrete",
  ["minecraft:polished_blackstone_brick_wall"] = "Polished Blackstone Brick Wall",
  ["minecraft:weathered_cut_copper_stairs"] = "Weathered Cut Copper Stairs", ["minecraft:poppy"] = "Poppy",
  ["minecraft:tripwire_hook"] = "Tripwire Hook", ["minecraft:flowering_azalea"] = "Flowering Azalea",
  ["minecraft:dead_tube_coral_block"] = "Dead Tube Coral Block", ["minecraft:bamboo_trapdoor"] = "Bamboo Trapdoor",
  ["minecraft:powder_snow"] = "Powder Snow", ["minecraft:jungle_trapdoor"] = "Jungle Trapdoor",
  ["minecraft:potted_azalea_bush"] = "Potted Azalea", ["minecraft:acacia_fence_gate"] = "Acacia Fence Gate",
  ["minecraft:red_stained_glass"] = "Red Stained Glass", ["minecraft:stone_bricks"] = "Stone Bricks",
  ["minecraft:observer"] = "Observer", ["minecraft:white_glazed_terracotta"] = "White Glazed Terracotta",
  ["minecraft:packed_ice"] = "Packed Ice", ["minecraft:birch_door"] = "Birch Door",
  ["minecraft:oak_pressure_plate"] = "Oak Pressure Plate", ["minecraft:lever"] = "Lever",
  ["minecraft:acacia_slab"] = "Acacia Slab", ["minecraft:birch_wall_sign"] = "Birch Wall Sign",
  ["minecraft:white_concrete"] = "White Concrete", ["minecraft:ice"] = "Ice",
  ["minecraft:dark_prismarine"] = "Dark Prismarine", ["minecraft:void_air"] = "Void Air",
  ["minecraft:purpur_stairs"] = "Purpur Stairs", ["minecraft:azure_bluet"] = "Azure Bluet",
  ["minecraft:light_blue_terracotta"] = "Light Blue Terracotta", ["minecraft:pink_candle_cake"] = "Cake with Pink Candle",
  ["minecraft:red_nether_brick_wall"] = "Red Nether Brick Wall", ["minecraft:birch_wood"] = "Birch Wood",
  ["minecraft:dark_oak_stairs"] = "Dark Oak Stairs", ["minecraft:snow_block"] = "Snow Block",
  ["minecraft:dead_bubble_coral_fan"] = "Dead Bubble Coral Fan", ["minecraft:diorite_wall"] = "Diorite Wall",
  ["minecraft:dark_oak_fence_gate"] = "Dark Oak Fence Gate", ["minecraft:crimson_nylium"] = "Crimson Nylium",
  ["minecraft:terracotta"] = "Terracotta", ["minecraft:warped_nylium"] = "Warped Nylium",
  ["minecraft:gray_candle_cake"] = "Cake with Gray Candle", ["minecraft:bubble_coral_wall_fan"] = "Bubble Coral Wall Fan",
  ["minecraft:polished_blackstone_wall"] = "Polished Blackstone Wall",
  ["minecraft:green_stained_glass"] = "Green Stained Glass", ["minecraft:slime_block"] = "Slime Block",
  ["minecraft:magenta_banner"] = "Magenta Banner", ["minecraft:weathered_copper"] = "Weathered Copper",
  ["minecraft:lime_concrete"] = "Lime Concrete", ["minecraft:dark_oak_slab"] = "Dark Oak Slab",
  ["minecraft:yellow_stained_glass_pane"] = "Yellow Stained Glass Pane", ["minecraft:blackstone"] = "Blackstone",
  ["minecraft:dead_horn_coral_fan"] = "Dead Horn Coral Fan", ["minecraft:crimson_sign"] = "Crimson Sign",
  ["minecraft:red_nether_brick_stairs"] = "Red Nether Brick Stairs", ["minecraft:cut_copper"] = "Cut Copper",
  ["minecraft:stripped_spruce_wood"] = "Stripped Spruce Wood", ["minecraft:shroomlight"] = "Shroomlight",
  ["minecraft:cyan_stained_glass_pane"] = "Cyan Stained Glass Pane",
  ["minecraft:brain_coral_block"] = "Brain Coral Block",
  ["minecraft:potted_bamboo"] = "Potted Bamboo", ["minecraft:sponge"] = "Sponge",
  ["minecraft:potted_cactus"] = "Potted Cactus", ["minecraft:red_nether_brick_slab"] = "Red Nether Brick Slab",
  ["minecraft:crimson_fungus"] = "Crimson Fungus", ["minecraft:jungle_stairs"] = "Jungle Stairs",
  ["minecraft:powder_snow_cauldron"] = "Powder Snow Cauldron",
  ["minecraft:light_gray_stained_glass"] = "Light Gray Stained Glass", ["minecraft:dropper"] = "Dropper",
  ["minecraft:ladder"] = "Ladder", ["minecraft:crimson_stem"] = "Crimson Stem",
  ["minecraft:honeycomb_block"] = "Honeycomb Block", ["minecraft:bamboo_hanging_sign"] = "Bamboo Hanging Sign",
  ["minecraft:cyan_carpet"] = "Cyan Carpet", ["minecraft:mangrove_wood"] = "Mangrove Wood",
  ["minecraft:emerald_ore"] = "Emerald Ore", ["minecraft:green_terracotta"] = "Green Terracotta",
  ["minecraft:light_blue_candle_cake"] = "Cake with Light Blue Candle", ["minecraft:water"] = "Water",
  ["minecraft:polished_blackstone_slab"] = "Polished Blackstone Slab",
  ["minecraft:stone_brick_stairs"] = "Stone Brick Stairs",
  ["minecraft:smooth_red_sandstone_stairs"] = "Smooth Red Sandstone Stairs", ["minecraft:yellow_wool"] = "Yellow Wool",
  ["minecraft:ochre_froglight"] = "Ochre Froglight", ["minecraft:magenta_concrete_powder"] = "Magenta Concrete Powder",
  ["minecraft:mud_brick_stairs"] = "Mud Brick Stairs", ["minecraft:mud"] = "Mud",
  ["minecraft:dead_brain_coral_wall_fan"] = "Dead Brain Coral Wall Fan", ["minecraft:azalea_leaves"] = "Azalea Leaves",
  ["minecraft:amethyst_block"] = "Block of Amethyst", ["minecraft:wall_torch"] = "Wall Torch",
  ["minecraft:mossy_cobblestone"] = "Mossy Cobblestone", ["minecraft:purple_bed"] = "Purple Bed",
  ["minecraft:flowering_azalea_leaves"] = "Flowering Azalea Leaves",
  ["minecraft:potted_brown_mushroom"] = "Potted Brown Mushroom", ["minecraft:allium"] = "Allium",
  ["minecraft:cut_copper_slab"] = "Cut Copper Slab", ["minecraft:shulker_box"] = "Shulker Box",
  ["minecraft:dark_oak_wall_sign"] = "Dark Oak Wall Sign", ["minecraft:kelp"] = "Kelp",
  ["minecraft:nether_gold_ore"] = "Nether Gold Ore", ["minecraft:dark_prismarine_slab"] = "Dark Prismarine Slab",
  ["minecraft:mud_brick_wall"] = "Mud Brick Wall", ["minecraft:white_concrete_powder"] = "White Concrete Powder",
  ["minecraft:purple_stained_glass"] = "Purple Stained Glass", ["minecraft:spruce_wall_sign"] = "Spruce Wall Sign",
  ["minecraft:white_wool"] = "White Wool", ["minecraft:pink_candle"] = "Pink Candle",
  ["minecraft:lime_carpet"] = "Lime Carpet", ["minecraft:prismarine_brick_slab"] = "Prismarine Brick Slab",
  ["minecraft:deepslate_lapis_ore"] = "Deepslate Lapis Lazuli Ore",
  ["minecraft:bamboo_wall_hanging_sign"] = "Bamboo Wall Hanging Sign", ["minecraft:powered_rail"] = "Powered Rail",
  ["minecraft:nether_bricks"] = "Nether Bricks", ["minecraft:birch_wall_hanging_sign"] = "Birch Wall Hanging Sign",
  ["minecraft:jungle_door"] = "Jungle Door", ["minecraft:bubble_coral"] = "Bubble Coral",
  ["minecraft:mangrove_wall_sign"] = "Mangrove Wall Sign", ["minecraft:purple_wool"] = "Purple Wool",
  ["minecraft:mossy_cobblestone_wall"] = "Mossy Cobblestone Wall", ["minecraft:dark_oak_planks"] = "Dark Oak Planks",
  ["minecraft:cobblestone_wall"] = "Cobblestone Wall",
  ["minecraft:potted_flowering_azalea_bush"] = "Potted Flowering Azalea", ["minecraft:mushroom_stem"] = "Mushroom Stem",
  ["minecraft:potted_white_tulip"] = "Potted White Tulip", ["minecraft:mangrove_propagule"] = "Mangrove Propagule",
  ["minecraft:smoker"] = "Smoker", ["minecraft:polished_andesite_stairs"] = "Polished Andesite Stairs",
  ["minecraft:stone_stairs"] = "Stone Stairs", ["minecraft:bamboo_fence"] = "Bamboo Fence",
  ["minecraft:stripped_warped_hyphae"] = "Stripped Warped Hyphae",
  ["minecraft:medium_amethyst_bud"] = "Medium Amethyst Bud", ["minecraft:jungle_hanging_sign"] = "Jungle Hanging Sign",
  ["minecraft:jungle_leaves"] = "Jungle Leaves", ["minecraft:player_wall_head"] = "Player Wall Head",
  ["minecraft:netherite_block"] = "Block of Netherite", ["minecraft:cyan_stained_glass"] = "Cyan Stained Glass",
  ["minecraft:tube_coral_wall_fan"] = "Tube Coral Wall Fan", ["minecraft:acacia_stairs"] = "Acacia Stairs",
  ["minecraft:crimson_slab"] = "Crimson Slab", ["minecraft:stripped_bamboo_block"] = "Block of Stripped Bamboo",
  ["minecraft:orange_tulip"] = "Orange Tulip", ["minecraft:nether_sprouts"] = "Nether Sprouts",
  ["minecraft:nether_brick_stairs"] = "Nether Brick Stairs", ["minecraft:green_candle"] = "Green Candle",
  ["minecraft:oak_hanging_sign"] = "Oak Hanging Sign", ["minecraft:tinted_glass"] = "Tinted Glass",
  ["minecraft:waxed_weathered_cut_copper"] = "Waxed Weathered Cut Copper",
  ["minecraft:carved_pumpkin"] = "Carved Pumpkin",
  ["minecraft:cake"] = "Cake", ["minecraft:podzol"] = "Podzol", ["minecraft:lime_terracotta"] = "Lime Terracotta",
  ["minecraft:jungle_sign"] = "Jungle Sign", ["minecraft:waxed_copper_block"] = "Waxed Block of Copper",
  ["minecraft:melon_stem"] = "Melon Stem", ["minecraft:polished_deepslate_stairs"] = "Polished Deepslate Stairs",
  ["minecraft:purple_shulker_box"] = "Purple Shulker Box", ["minecraft:quartz_stairs"] = "Quartz Stairs",
  ["minecraft:spruce_sign"] = "Spruce Sign", ["minecraft:brain_coral"] = "Brain Coral",
  ["minecraft:light_gray_concrete_powder"] = "Light Gray Concrete Powder",
  ["minecraft:spruce_pressure_plate"] = "Spruce Pressure Plate", ["minecraft:crimson_trapdoor"] = "Crimson Trapdoor",
  ["minecraft:dark_oak_button"] = "Dark Oak Button", ["minecraft:oak_button"] = "Oak Button",
  ["minecraft:stone_slab"] = "Stone Slab", ["minecraft:jungle_wall_sign"] = "Jungle Wall Sign",
  ["minecraft:cobblestone_stairs"] = "Cobblestone Stairs", ["minecraft:redstone_torch"] = "Redstone Torch",
  ["minecraft:red_mushroom_block"] = "Red Mushroom Block", ["minecraft:oak_leaves"] = "Oak Leaves",
  ["minecraft:light_blue_shulker_box"] = "Light Blue Shulker Box", ["minecraft:potatoes"] = "Potatoes",
  ["minecraft:dead_fire_coral"] = "Dead Fire Coral", ["minecraft:waxed_exposed_copper"] = "Waxed Exposed Copper",
  ["minecraft:polished_blackstone_brick_slab"] = "Polished Blackstone Brick Slab",
  ["minecraft:orange_bed"] = "Orange Bed",
  ["minecraft:brown_terracotta"] = "Brown Terracotta", ["minecraft:bamboo_sign"] = "Bamboo Sign",
  ["minecraft:quartz_pillar"] = "Quartz Pillar", ["minecraft:waxed_oxidized_cut_copper"] = "Waxed Oxidized Cut Copper",
  ["minecraft:polished_blackstone_pressure_plate"] = "Polished Blackstone Pressure Plate",
  ["minecraft:pumpkin_stem"] = "Pumpkin Stem", ["minecraft:cyan_bed"] = "Cyan Bed",
  ["minecraft:light_gray_stained_glass_pane"] = "Light Gray Stained Glass Pane",
  ["minecraft:infested_cobblestone"] = "Infested Cobblestone", ["minecraft:gray_candle"] = "Gray Candle",
  ["minecraft:obsidian"] = "Obsidian", ["minecraft:dark_oak_sign"] = "Dark Oak Sign",
  ["minecraft:acacia_wall_hanging_sign"] = "Acacia Wall Hanging Sign", ["minecraft:purpur_pillar"] = "Purpur Pillar",
  ["minecraft:warped_sign"] = "Warped Sign", ["minecraft:pink_carpet"] = "Pink Carpet",
  ["minecraft:diorite_stairs"] = "Diorite Stairs", ["minecraft:crying_obsidian"] = "Crying Obsidian",
  ["minecraft:repeating_command_block"] = "Repeating Command Block",
  ["minecraft:mossy_cobblestone_slab"] = "Mossy Cobblestone Slab",
  ["minecraft:birch_hanging_sign"] = "Birch Hanging Sign",
  ["minecraft:yellow_stained_glass"] = "Yellow Stained Glass", ["minecraft:brown_candle_cake"] = "Cake with Brown Candle",
  ["minecraft:barrier"] = "Barrier", ["minecraft:bamboo_wall_sign"] = "Bamboo Wall Sign",
  ["minecraft:dead_tube_coral_fan"] = "Dead Tube Coral Fan", ["minecraft:mycelium"] = "Mycelium",
  ["minecraft:acacia_fence"] = "Acacia Fence", ["minecraft:warped_hanging_sign"] = "Warped Hanging Sign",
  ["minecraft:large_amethyst_bud"] = "Large Amethyst Bud",
  ["minecraft:stripped_mangrove_wood"] = "Stripped Mangrove Wood",
  ["minecraft:weathered_cut_copper_slab"] = "Weathered Cut Copper Slab",
  ["minecraft:stripped_spruce_log"] = "Stripped Spruce Log",
  ["minecraft:oxidized_cut_copper_slab"] = "Oxidized Cut Copper Slab",
  ["minecraft:chiseled_nether_bricks"] = "Chiseled Nether Bricks", ["minecraft:birch_log"] = "Birch Log",
  ["minecraft:orange_glazed_terracotta"] = "Orange Glazed Terracotta",
  ["minecraft:stripped_jungle_log"] = "Stripped Jungle Log", ["minecraft:gray_wool"] = "Gray Wool",
  ["minecraft:white_bed"] = "White Bed", ["minecraft:crimson_hyphae"] = "Crimson Hyphae",
  ["minecraft:honey_block"] = "Honey Block", ["minecraft:crimson_stairs"] = "Crimson Stairs",
  ["minecraft:cyan_candle"] = "Cyan Candle", ["minecraft:warped_stem"] = "Warped Stem", ["minecraft:bedrock"] = "Bedrock",
  ["minecraft:lantern"] = "Lantern", ["minecraft:deepslate_tile_wall"] = "Deepslate Tile Wall",
  ["minecraft:warped_slab"] = "Warped Slab", ["minecraft:crimson_pressure_plate"] = "Crimson Pressure Plate",
  ["minecraft:vine"] = "Vines", ["minecraft:attached_pumpkin_stem"] = "Attached Pumpkin Stem",
  ["minecraft:tripwire"] = "Tripwire", ["minecraft:raw_copper_block"] = "Block of Raw Copper",
  ["minecraft:birch_sign"] = "Birch Sign", ["minecraft:heavy_weighted_pressure_plate"] = "Heavy Weighted Pressure Plate",
  ["minecraft:hanging_roots"] = "Hanging Roots", ["minecraft:soul_fire"] = "Soul Fire",
  ["minecraft:damaged_anvil"] = "Damaged Anvil", ["minecraft:quartz_bricks"] = "Quartz Bricks",
  ["minecraft:birch_fence_gate"] = "Birch Fence Gate", ["minecraft:piglin_head"] = "Piglin Head",
  ["minecraft:bamboo_slab"] = "Bamboo Slab", ["minecraft:oak_trapdoor"] = "Oak Trapdoor",
  ["minecraft:jack_o_lantern"] = "Jack o'Lantern", ["minecraft:purple_candle"] = "Purple Candle",
  ["minecraft:green_concrete_powder"] = "Green Concrete Powder", ["minecraft:yellow_carpet"] = "Yellow Carpet",
  ["minecraft:stripped_birch_wood"] = "Stripped Birch Wood",
  ["minecraft:polished_deepslate_wall"] = "Polished Deepslate Wall", ["minecraft:barrel"] = "Barrel",
  ["minecraft:horn_coral_wall_fan"] = "Horn Coral Wall Fan",
  ["minecraft:polished_blackstone_button"] = "Polished Blackstone Button", ["minecraft:magenta_bed"] = "Magenta Bed",
  ["minecraft:candle_cake"] = "Cake with Candle", ["minecraft:dead_bubble_coral"] = "Dead Bubble Coral",
  ["minecraft:furnace"] = "Furnace", ["minecraft:lime_stained_glass"] = "Lime Stained Glass",
  ["minecraft:oak_fence_gate"] = "Oak Fence Gate", ["minecraft:blue_stained_glass"] = "Blue Stained Glass",
  ["minecraft:stripped_birch_log"] = "Stripped Birch Log", ["minecraft:dirt_path"] = "Dirt Path",
  ["minecraft:weeping_vines"] = "Weeping Vines", ["minecraft:dead_brain_coral_fan"] = "Dead Brain Coral Fan",
  ["minecraft:dark_oak_trapdoor"] = "Dark Oak Trapdoor", ["minecraft:magenta_wool"] = "Magenta Wool",
  ["minecraft:potted_azure_bluet"] = "Potted Azure Bluet", ["minecraft:big_dripleaf"] = "Big Dripleaf",
  ["minecraft:oak_wall_sign"] = "Oak Wall Sign", ["minecraft:oxidized_cut_copper_stairs"] = "Oxidized Cut Copper Stairs",
  ["minecraft:piston"] = "Piston", ["minecraft:cocoa"] = "Cocoa",
  ["minecraft:white_stained_glass"] = "White Stained Glass",
  ["minecraft:wheat"] = "Wheat Crops", ["minecraft:crimson_fence_gate"] = "Crimson Fence Gate",
  ["minecraft:crafting_table"] = "Crafting Table", ["minecraft:lapis_ore"] = "Lapis Lazuli Ore",
  ["minecraft:mangrove_button"] = "Mangrove Button", ["minecraft:chipped_anvil"] = "Chipped Anvil",
  ["minecraft:bamboo_mosaic_stairs"] = "Bamboo Mosaic Stairs", ["minecraft:acacia_button"] = "Acacia Button",
  ["minecraft:sugar_cane"] = "Sugar Cane", ["minecraft:potted_crimson_roots"] = "Potted Crimson Roots",
  ["minecraft:azalea"] = "Azalea", ["minecraft:light_blue_concrete_powder"] = "Light Blue Concrete Powder",
  ["minecraft:orange_terracotta"] = "Orange Terracotta", ["minecraft:end_portal"] = "End Portal",
  ["minecraft:trapped_chest"] = "Trapped Chest", ["minecraft:blue_candle_cake"] = "Cake with Blue Candle",
  ["minecraft:potted_red_mushroom"] = "Potted Red Mushroom",
  ["minecraft:chiseled_polished_blackstone"] = "Chiseled Polished Blackstone",
  ["minecraft:waxed_exposed_cut_copper"] = "Waxed Exposed Cut Copper", ["minecraft:conduit"] = "Conduit",
  ["minecraft:birch_fence"] = "Birch Fence", ["minecraft:smooth_red_sandstone_slab"] = "Smooth Red Sandstone Slab",
  ["minecraft:pink_concrete_powder"] = "Pink Concrete Powder", ["minecraft:gray_terracotta"] = "Gray Terracotta",
  ["minecraft:sculk_sensor"] = "Sculk Sensor",
  ["minecraft:polished_blackstone_brick_stairs"] = "Polished Blackstone Brick Stairs",
  ["minecraft:acacia_sapling"] = "Acacia Sapling", ["minecraft:warped_wall_hanging_sign"] = "Warped Wall Hanging Sign",
  ["minecraft:cornflower"] = "Cornflower", ["minecraft:blue_wool"] = "Blue Wool",
  ["minecraft:polished_deepslate"] = "Polished Deepslate", ["minecraft:crimson_wall_sign"] = "Crimson Wall Sign",
  ["minecraft:pink_stained_glass"] = "Pink Stained Glass", ["minecraft:magenta_terracotta"] = "Magenta Terracotta",
  ["minecraft:redstone_block"] = "Block of Redstone", ["minecraft:end_portal_frame"] = "End Portal Frame",
  ["minecraft:structure_block"] = "Structure Block", ["minecraft:moving_piston"] = "Moving Piston",
  ["minecraft:andesite_slab"] = "Andesite Slab", ["minecraft:cobbled_deepslate_stairs"] = "Cobbled Deepslate Stairs",
  ["minecraft:blackstone_slab"] = "Blackstone Slab", ["minecraft:light_gray_bed"] = "Light Gray Bed",
  ["minecraft:jungle_log"] = "Jungle Log", ["minecraft:quartz_block"] = "Block of Quartz",
  ["minecraft:brown_concrete_powder"] = "Brown Concrete Powder", ["minecraft:cactus"] = "Cactus",
  ["minecraft:wither_skeleton_wall_skull"] = "Wither Skeleton Wall Skull",
  ["minecraft:prismarine_wall"] = "Prismarine Wall", ["minecraft:cut_sandstone_slab"] = "Cut Sandstone Slab",
  ["minecraft:melon"] = "Melon", ["minecraft:mangrove_hanging_sign"] = "Mangrove Hanging Sign",
  ["minecraft:polished_granite"] = "Polished Granite", ["minecraft:pink_stained_glass_pane"] = "Pink Stained Glass Pane",
  ["minecraft:detector_rail"] = "Detector Rail", ["minecraft:potted_spruce_sapling"] = "Potted Spruce Sapling",
  ["minecraft:redstone_lamp"] = "Redstone Lamp", ["minecraft:smooth_sandstone"] = "Smooth Sandstone",
  ["minecraft:budding_amethyst"] = "Budding Amethyst", ["minecraft:deepslate"] = "Deepslate",
  ["minecraft:red_bed"] = "Red Bed", ["minecraft:horn_coral_block"] = "Horn Coral Block",
  ["minecraft:dead_fire_coral_wall_fan"] = "Dead Fire Coral Wall Fan",
  ["minecraft:polished_diorite_stairs"] = "Polished Diorite Stairs", ["minecraft:dark_oak_log"] = "Dark Oak Log",
  ["minecraft:glowstone"] = "Glowstone", ["minecraft:sea_pickle"] = "Sea Pickle",
  ["minecraft:spruce_trapdoor"] = "Spruce Trapdoor", ["minecraft:mangrove_fence_gate"] = "Mangrove Fence Gate",
  ["minecraft:infested_cracked_stone_bricks"] = "Infested Cracked Stone Bricks",
  ["minecraft:oak_wall_hanging_sign"] = "Oak Wall Hanging Sign",
  ["minecraft:redstone_wall_torch"] = "Redstone Wall Torch",
  ["minecraft:acacia_wood"] = "Acacia Wood", ["minecraft:jungle_slab"] = "Jungle Slab",
  ["minecraft:warped_fungus"] = "Warped Fungus", ["minecraft:waxed_weathered_copper"] = "Waxed Weathered Copper",
  ["minecraft:dead_fire_coral_block"] = "Dead Fire Coral Block", ["minecraft:green_concrete"] = "Green Concrete",
  ["minecraft:red_shulker_box"] = "Red Shulker Box", ["minecraft:oak_log"] = "Oak Log",
  ["minecraft:light_gray_candle_cake"] = "Cake with Light Gray Candle", ["minecraft:crimson_planks"] = "Crimson Planks",
  ["minecraft:granite_slab"] = "Granite Slab", ["minecraft:potted_birch_sapling"] = "Potted Birch Sapling",
  ["minecraft:turtle_egg"] = "Turtle Egg", ["minecraft:hopper"] = "Hopper", ["minecraft:grass_block"] = "Grass Block",
  ["minecraft:tube_coral_block"] = "Tube Coral Block", ["minecraft:warped_fence_gate"] = "Warped Fence Gate",
  ["minecraft:sand"] = "Sand", ["minecraft:blue_candle"] = "Blue Candle",
  ["minecraft:lime_glazed_terracotta"] = "Lime Glazed Terracotta", ["minecraft:dark_oak_leaves"] = "Dark Oak Leaves",
  ["minecraft:jungle_fence"] = "Jungle Fence", ["minecraft:cyan_shulker_box"] = "Cyan Shulker Box",
  ["minecraft:blackstone_stairs"] = "Blackstone Stairs", ["minecraft:red_wool"] = "Red Wool",
  ["minecraft:birch_sapling"] = "Birch Sapling", ["minecraft:brown_bed"] = "Brown Bed",
  ["minecraft:orange_concrete_powder"] = "Orange Concrete Powder", ["minecraft:lightning_rod"] = "Lightning Rod",
  ["minecraft:potted_cornflower"] = "Potted Cornflower", ["minecraft:amethyst_cluster"] = "Amethyst Cluster",
  ["minecraft:black_shulker_box"] = "Black Shulker Box",
  ["minecraft:exposed_cut_copper_stairs"] = "Exposed Cut Copper Stairs", ["minecraft:mud_brick_slab"] = "Mud Brick Slab",
  ["minecraft:light_blue_stained_glass"] = "Light Blue Stained Glass", ["minecraft:gray_carpet"] = "Gray Carpet",
  ["minecraft:mangrove_door"] = "Mangrove Door", ["minecraft:orange_stained_glass"] = "Orange Stained Glass",
  ["minecraft:warped_door"] = "Warped Door", ["minecraft:copper_block"] = "Block of Copper",
  ["minecraft:dead_fire_coral_fan"] = "Dead Fire Coral Fan", ["minecraft:birch_planks"] = "Birch Planks",
  ["minecraft:cracked_stone_bricks"] = "Cracked Stone Bricks", ["minecraft:white_shulker_box"] = "White Shulker Box",
  ["minecraft:blue_shulker_box"] = "Blue Shulker Box", ["minecraft:cauldron"] = "Cauldron",
  ["minecraft:purpur_slab"] = "Purpur Slab",
  ["minecraft:waxed_weathered_cut_copper_slab"] = "Waxed Weathered Cut Copper Slab",
  ["minecraft:jungle_button"] = "Jungle Button", ["minecraft:light_blue_concrete"] = "Light Blue Concrete",
  ["minecraft:potted_dark_oak_sapling"] = "Potted Dark Oak Sapling", ["minecraft:bee_nest"] = "Bee Nest",
  ["minecraft:prismarine"] = "Prismarine", ["minecraft:repeater"] = "Redstone Repeater",
  ["minecraft:green_stained_glass_pane"] = "Green Stained Glass Pane",
  ["minecraft:chiseled_deepslate"] = "Chiseled Deepslate", ["minecraft:calcite"] = "Calcite",
  ["minecraft:stone_button"] = "Stone Button", ["minecraft:dead_bush"] = "Dead Bush",
  ["minecraft:bamboo_mosaic_slab"] = "Bamboo Mosaic Slab", ["minecraft:warped_hyphae"] = "Warped Hyphae",
  ["minecraft:soul_sand"] = "Soul Sand", ["minecraft:loom"] = "Loom", ["minecraft:rooted_dirt"] = "Rooted Dirt",
  ["minecraft:yellow_glazed_terracotta"] = "Yellow Glazed Terracotta", ["minecraft:polished_basalt"] = "Polished Basalt",
  ["minecraft:blue_bed"] = "Blue Bed", ["minecraft:red_stained_glass_pane"] = "Red Stained Glass Pane",
  ["minecraft:spruce_hanging_sign"] = "Spruce Hanging Sign", ["minecraft:spruce_planks"] = "Spruce Planks",
  ["minecraft:dead_brain_coral_block"] = "Dead Brain Coral Block", ["minecraft:piston_head"] = "Piston Head",
  ["minecraft:sandstone_stairs"] = "Sandstone Stairs", ["minecraft:farmland"] = "Farmland",
  ["minecraft:reinforced_deepslate"] = "Reinforced Deepslate", ["minecraft:oak_sapling"] = "Oak Sapling",
  ["minecraft:basalt"] = "Basalt", ["minecraft:exposed_copper"] = "Exposed Copper",
  ["minecraft:potted_warped_fungus"] = "Potted Warped Fungus", ["minecraft:tube_coral_fan"] = "Tube Coral Fan",
  ["minecraft:command_block"] = "Command Block", ["minecraft:purple_terracotta"] = "Purple Terracotta",
  ["minecraft:chain"] = "Chain", ["minecraft:birch_pressure_plate"] = "Birch Pressure Plate",
  ["minecraft:exposed_cut_copper_slab"] = "Exposed Cut Copper Slab",
  ["minecraft:big_dripleaf_stem"] = "Big Dripleaf Stem",
  ["minecraft:waxed_oxidized_cut_copper_slab"] = "Waxed Oxidized Cut Copper Slab",
  ["minecraft:pink_terracotta"] = "Pink Terracotta", ["minecraft:soul_soil"] = "Soul Soil",
  ["minecraft:yellow_candle"] = "Yellow Candle", ["minecraft:blast_furnace"] = "Blast Furnace",
  ["minecraft:polished_diorite_slab"] = "Polished Diorite Slab",
  ["minecraft:brain_coral_wall_fan"] = "Brain Coral Wall Fan",
  ["minecraft:dead_horn_coral_block"] = "Dead Horn Coral Block",
  ["minecraft:deepslate_redstone_ore"] = "Deepslate Redstone Ore", ["minecraft:lava_cauldron"] = "Lava Cauldron",
  ["minecraft:cartography_table"] = "Cartography Table", ["minecraft:purple_candle_cake"] = "Cake with Purple Candle",
  ["minecraft:purple_concrete_powder"] = "Purple Concrete Powder",
  ["minecraft:lily_of_the_valley"] = "Lily of the Valley",
  ["minecraft:warped_stairs"] = "Warped Stairs", ["minecraft:composter"] = "Composter",
  ["minecraft:potted_red_tulip"] = "Potted Red Tulip", ["minecraft:brown_mushroom_block"] = "Brown Mushroom Block",
  ["minecraft:bamboo_stairs"] = "Bamboo Stairs", ["minecraft:white_stained_glass_pane"] = "White Stained Glass Pane",
  ["minecraft:lime_banner"] = "Lime Banner", ["minecraft:lily_pad"] = "Lily Pad", ["minecraft:brick_slab"] = "Brick Slab",
  ["minecraft:twisting_vines_plant"] = "Twisting Vines Plant",
  ["minecraft:polished_granite_stairs"] = "Polished Granite Stairs",
  ["minecraft:warped_pressure_plate"] = "Warped Pressure Plate", ["minecraft:daylight_detector"] = "Daylight Detector",
  ["minecraft:smooth_red_sandstone"] = "Smooth Red Sandstone", ["minecraft:mangrove_log"] = "Mangrove Log",
  ["minecraft:gray_concrete"] = "Gray Concrete", ["minecraft:stripped_warped_stem"] = "Stripped Warped Stem",
  ["minecraft:soul_campfire"] = "Soul Campfire", ["minecraft:purpur_block"] = "Purpur Block",
  ["minecraft:magenta_stained_glass"] = "Magenta Stained Glass", ["minecraft:bubble_coral_fan"] = "Bubble Coral Fan",
  ["minecraft:smithing_table"] = "Smithing Table", ["minecraft:stripped_acacia_wood"] = "Stripped Acacia Wood",
  ["minecraft:tnt"] = "TNT", ["minecraft:cave_air"] = "Cave Air", ["minecraft:brown_carpet"] = "Brown Carpet",
  ["minecraft:tall_seagrass"] = "Tall Seagrass", ["minecraft:mangrove_fence"] = "Mangrove Fence",
  ["minecraft:lime_bed"] = "Lime Bed", ["minecraft:red_banner"] = "Red Banner",
  ["minecraft:cracked_polished_blackstone_bricks"] = "Cracked Polished Blackstone Bricks",
  ["minecraft:warped_wart_block"] = "Warped Wart Block", ["minecraft:cave_vines"] = "Cave Vines",
  ["minecraft:deepslate_tile_stairs"] = "Deepslate Tile Stairs", ["minecraft:cyan_wool"] = "Cyan Wool",
  ["minecraft:deepslate_bricks"] = "Deepslate Bricks", ["minecraft:blue_terracotta"] = "Blue Terracotta",
  ["minecraft:fire_coral_block"] = "Fire Coral Block", ["minecraft:cobblestone"] = "Cobblestone",
  ["minecraft:soul_lantern"] = "Soul Lantern", ["minecraft:magenta_shulker_box"] = "Magenta Shulker Box",
  ["minecraft:infested_deepslate"] = "Infested Deepslate", ["minecraft:wither_skeleton_skull"] = "Wither Skeleton Skull",
  ["minecraft:sculk_catalyst"] = "Sculk Catalyst", ["minecraft:prismarine_slab"] = "Prismarine Slab",
  ["minecraft:weeping_vines_plant"] = "Weeping Vines Plant", ["minecraft:scaffolding"] = "Scaffolding",
  ["minecraft:green_banner"] = "Green Banner", ["minecraft:twisting_vines"] = "Twisting Vines",
  ["minecraft:red_carpet"] = "Red Carpet", ["minecraft:brick_stairs"] = "Brick Stairs",
  ["minecraft:nether_brick_fence"] = "Nether Brick Fence", ["minecraft:red_tulip"] = "Red Tulip",
  ["minecraft:light_blue_wool"] = "Light Blue Wool", ["minecraft:light_blue_carpet"] = "Light Blue Carpet",
  ["minecraft:dispenser"] = "Dispenser", ["minecraft:deepslate_tile_slab"] = "Deepslate Tile Slab",
  ["minecraft:potted_oak_sapling"] = "Potted Oak Sapling", ["minecraft:end_rod"] = "End Rod",
  ["minecraft:yellow_terracotta"] = "Yellow Terracotta", ["minecraft:light"] = "Light",
  ["minecraft:nether_wart"] = "Nether Wart", ["minecraft:fletching_table"] = "Fletching Table",
  ["minecraft:black_stained_glass"] = "Black Stained Glass", ["minecraft:mossy_stone_bricks"] = "Mossy Stone Bricks",
  ["minecraft:black_glazed_terracotta"] = "Black Glazed Terracotta", ["minecraft:packed_mud"] = "Packed Mud",
  ["minecraft:cut_copper_stairs"] = "Cut Copper Stairs", ["minecraft:chiseled_stone_bricks"] = "Chiseled Stone Bricks",
  ["minecraft:spore_blossom"] = "Spore Blossom", ["minecraft:exposed_cut_copper"] = "Exposed Cut Copper",
  ["minecraft:brewing_stand"] = "Brewing Stand", ["minecraft:light_gray_concrete"] = "Light Gray Concrete",
  ["minecraft:wet_sponge"] = "Wet Sponge", ["minecraft:grass"] = "Grass", ["minecraft:blue_ice"] = "Blue Ice",
  ["minecraft:red_candle"] = "Red Candle", ["minecraft:nether_brick_slab"] = "Nether Brick Slab",
  ["minecraft:red_concrete"] = "Red Concrete", ["minecraft:spruce_fence_gate"] = "Spruce Fence Gate",
  ["minecraft:pointed_dripstone"] = "Pointed Dripstone", ["minecraft:small_dripleaf"] = "Small Dripleaf",
  ["minecraft:horn_coral"] = "Horn Coral", ["minecraft:zombie_head"] = "Zombie Head", ["minecraft:lilac"] = "Lilac",
  ["minecraft:blue_glazed_terracotta"] = "Blue Glazed Terracotta",
  ["minecraft:purple_stained_glass_pane"] = "Purple Stained Glass Pane", ["minecraft:hay_block"] = "Hay Bale",
  ["minecraft:bubble_column"] = "Bubble Column", ["minecraft:potted_orange_tulip"] = "Potted Orange Tulip",
  ["minecraft:potted_wither_rose"] = "Potted Wither Rose", ["minecraft:green_bed"] = "Green Bed",
  ["minecraft:potted_crimson_fungus"] = "Potted Crimson Fungus", ["minecraft:smooth_basalt"] = "Smooth Basalt",
  ["minecraft:light_gray_glazed_terracotta"] = "Light Gray Glazed Terracotta",
  ["minecraft:green_candle_cake"] = "Cake with Green Candle", ["minecraft:grindstone"] = "Grindstone",
  ["minecraft:cobbled_deepslate"] = "Cobbled Deepslate", ["minecraft:cave_vines_plant"] = "Cave Vines Plant",
  ["minecraft:stripped_mangrove_log"] = "Stripped Mangrove Log", ["minecraft:small_amethyst_bud"] = "Small Amethyst Bud",
  ["minecraft:stripped_acacia_log"] = "Stripped Acacia Log", ["minecraft:birch_slab"] = "Birch Slab",
  ["minecraft:stripped_oak_wood"] = "Stripped Oak Wood", ["minecraft:gray_bed"] = "Gray Bed",
  ["minecraft:red_sand"] = "Red Sand", ["minecraft:white_candle"] = "White Candle",
  ["minecraft:light_gray_candle"] = "Light Gray Candle", ["minecraft:spruce_stairs"] = "Spruce Stairs",
  ["minecraft:iron_ore"] = "Iron Ore", ["minecraft:infested_stone"] = "Infested Stone",
  ["minecraft:nether_quartz_ore"] = "Nether Quartz Ore", ["minecraft:glass_pane"] = "Glass Pane",
  ["minecraft:dark_oak_sapling"] = "Dark Oak Sapling", }
