---@type {[string]:string}
return { soul_sand = "Soul Sand", mangrove_hanging_sign = "Mangrove Hanging Sign",
  magenta_stained_glass_pane = "Magenta Stained Glass Pane", mangrove_door = "Mangrove Door", dead_bush = "Dead Bush",
  mangrove_planks = "Mangrove Planks", blue_concrete_powder = "Blue Concrete Powder",
  nether_brick_fence = "Nether Brick Fence", black_stained_glass = "Black Stained Glass", hopper = "Hopper",
  lily_of_the_valley = "Lily of the Valley", snow_block = "Snow Block",
  mossy_stone_brick_stairs = "Mossy Stone Brick Stairs", lilac = "Lilac", mud_brick_slab = "Mud Brick Slab",
  orange_concrete = "Orange Concrete", mangrove_leaves = "Mangrove Leaves", bamboo_stairs = "Bamboo Stairs",
  dead_horn_coral_block = "Dead Horn Coral Block", end_stone_brick_wall = "End Stone Brick Wall",
  stripped_oak_wood = "Stripped Oak Wood", deepslate_bricks = "Deepslate Bricks", cobblestone = "Cobblestone",
  light_gray_stained_glass = "Light Gray Stained Glass", bee_nest = "Bee Nest",
  polished_blackstone_pressure_plate = "Polished Blackstone Pressure Plate", potted_oxeye_daisy = "Potted Oxeye Daisy",
  jungle_wall_hanging_sign = "Jungle Wall Hanging Sign", red_stained_glass = "Red Stained Glass",
  gray_carpet = "Gray Carpet", tube_coral_block = "Tube Coral Block", potted_crimson_roots = "Potted Crimson Roots",
  verdant_froglight = "Verdant Froglight", spruce_planks = "Spruce Planks",
  light_weighted_pressure_plate = "Light Weighted Pressure Plate", red_glazed_terracotta = "Red Glazed Terracotta",
  exposed_copper = "Exposed Copper", deepslate_copper_ore = "Deepslate Copper Ore",
  nether_wart_block = "Nether Wart Block",
  deepslate_iron_ore = "Deepslate Iron Ore", polished_deepslate_slab = "Polished Deepslate Slab",
  potted_mangrove_propagule = "Potted Mangrove Propagule", jungle_leaves = "Jungle Leaves",
  deepslate_diamond_ore = "Deepslate Diamond Ore", red_candle = "Red Candle",
  green_stained_glass_pane = "Green Stained Glass Pane", gray_stained_glass_pane = "Gray Stained Glass Pane",
  quartz_block = "Block of Quartz", spruce_pressure_plate = "Spruce Pressure Plate", sculk_shrieker = "Sculk Shrieker",
  nether_wart = "Nether Wart", gilded_blackstone = "Gilded Blackstone", warped_fence_gate = "Warped Fence Gate",
  potted_brown_mushroom = "Potted Brown Mushroom", soul_soil = "Soul Soil",
  waxed_exposed_cut_copper_slab = "Waxed Exposed Cut Copper Slab", lava_cauldron = "Lava Cauldron",
  dandelion = "Dandelion",
  sweet_berry_bush = "Sweet Berry Bush", oak_pressure_plate = "Oak Pressure Plate", mangrove_button = "Mangrove Button",
  quartz_bricks = "Quartz Bricks", diorite_wall = "Diorite Wall", birch_wall_sign = "Birch Wall Sign",
  crimson_wall_sign = "Crimson Wall Sign", farmland = "Farmland", white_candle = "White Candle", torch = "Torch",
  deepslate_redstone_ore = "Deepslate Redstone Ore", blast_furnace = "Blast Furnace",
  pink_glazed_terracotta = "Pink Glazed Terracotta", cut_copper_stairs = "Cut Copper Stairs",
  brown_mushroom = "Brown Mushroom", sculk = "Sculk", daylight_detector = "Daylight Detector", ladder = "Ladder",
  pumpkin = "Pumpkin", warped_stairs = "Warped Stairs", copper_ore = "Copper Ore",
  mossy_cobblestone_wall = "Mossy Cobblestone Wall", granite_slab = "Granite Slab", wall_torch = "Wall Torch",
  blue_candle = "Blue Candle", cave_vines = "Cave Vines", brain_coral = "Brain Coral",
  mossy_cobblestone_slab = "Mossy Cobblestone Slab", stone_brick_slab = "Stone Brick Slab",
  raw_copper_block = "Block of Raw Copper", green_concrete_powder = "Green Concrete Powder",
  repeating_command_block = "Repeating Command Block", yellow_carpet = "Yellow Carpet",
  nether_brick_slab = "Nether Brick Slab", light_gray_banner = "Light Gray Banner",
  spruce_hanging_sign = "Spruce Hanging Sign", stone_stairs = "Stone Stairs", cyan_banner = "Cyan Banner",
  waxed_oxidized_copper = "Waxed Oxidized Copper", black_concrete = "Black Concrete",
  acacia_pressure_plate = "Acacia Pressure Plate", ice = "Ice", lime_candle = "Lime Candle",
  stone_pressure_plate = "Stone Pressure Plate", deepslate_tiles = "Deepslate Tiles", dark_oak_log = "Dark Oak Log",
  bamboo_fence_gate = "Bamboo Fence Gate", birch_wood = "Birch Wood", light_blue_concrete = "Light Blue Concrete",
  mangrove_propagule = "Mangrove Propagule", yellow_banner = "Yellow Banner",
  white_glazed_terracotta = "White Glazed Terracotta", dead_fire_coral = "Dead Fire Coral", soul_lantern = "Soul Lantern",
  black_stained_glass_pane = "Black Stained Glass Pane", deepslate_brick_slab = "Deepslate Brick Slab",
  pink_terracotta = "Pink Terracotta", candle = "Candle", black_carpet = "Black Carpet", soul_campfire = "Soul Campfire",
  seagrass = "Seagrass", red_sandstone_wall = "Red Sandstone Wall", crimson_fungus = "Crimson Fungus",
  smooth_stone_slab = "Smooth Stone Slab", cartography_table = "Cartography Table", cauldron = "Cauldron",
  dispenser = "Dispenser", comparator = "Redstone Comparator", crimson_stem = "Crimson Stem",
  dead_brain_coral = "Dead Brain Coral", cyan_glazed_terracotta = "Cyan Glazed Terracotta", iron_ore = "Iron Ore",
  quartz_stairs = "Quartz Stairs", cut_sandstone = "Cut Sandstone", sandstone_stairs = "Sandstone Stairs",
  exposed_cut_copper_stairs = "Exposed Cut Copper Stairs", polished_blackstone = "Polished Blackstone", cake = "Cake",
  beetroots = "Beetroots", soul_wall_torch = "Soul Wall Torch", fire_coral_fan = "Fire Coral Fan",
  green_glazed_terracotta = "Green Glazed Terracotta", fire = "Fire", polished_andesite = "Polished Andesite",
  lime_stained_glass_pane = "Lime Stained Glass Pane", oxidized_cut_copper = "Oxidized Cut Copper",
  chiseled_quartz_block = "Chiseled Quartz Block", oak_fence_gate = "Oak Fence Gate", bell = "Bell", snow = "Snow",
  sculk_vein = "Sculk Vein", warped_wall_sign = "Warped Wall Sign", smithing_table = "Smithing Table",
  frosted_ice = "Frosted Ice", chiseled_polished_blackstone = "Chiseled Polished Blackstone",
  lime_concrete_powder = "Lime Concrete Powder", acacia_wall_hanging_sign = "Acacia Wall Hanging Sign",
  jungle_sapling = "Jungle Sapling", dragon_egg = "Dragon Egg", campfire = "Campfire",
  prismarine_wall = "Prismarine Wall",
  soul_torch = "Soul Torch", cut_red_sandstone_slab = "Cut Red Sandstone Slab", spruce_leaves = "Spruce Leaves",
  oak_door = "Oak Door", cobbled_deepslate_wall = "Cobbled Deepslate Wall", birch_trapdoor = "Birch Trapdoor",
  grass = "Grass", grindstone = "Grindstone", grass_block = "Grass Block",
  red_nether_brick_wall = "Red Nether Brick Wall",
  flowering_azalea = "Flowering Azalea", brick_slab = "Brick Slab", iron_block = "Block of Iron",
  cave_vines_plant = "Cave Vines Plant", blue_concrete = "Blue Concrete", dark_oak_slab = "Dark Oak Slab",
  blue_banner = "Blue Banner", repeater = "Redstone Repeater", dark_oak_button = "Dark Oak Button",
  weathered_cut_copper = "Weathered Cut Copper", spruce_slab = "Spruce Slab", gray_candle_cake = "Cake with Gray Candle",
  jungle_stairs = "Jungle Stairs", mangrove_fence = "Mangrove Fence", pink_candle_cake = "Cake with Pink Candle",
  deepslate_lapis_ore = "Deepslate Lapis Lazuli Ore", azure_bluet = "Azure Bluet", oak_sapling = "Oak Sapling",
  dead_tube_coral_fan = "Dead Tube Coral Fan", crimson_roots = "Crimson Roots", gray_shulker_box = "Gray Shulker Box",
  infested_stone = "Infested Stone", honey_block = "Honey Block", cyan_wool = "Cyan Wool",
  lime_shulker_box = "Lime Shulker Box", green_wool = "Green Wool", green_carpet = "Green Carpet",
  polished_blackstone_slab = "Polished Blackstone Slab", glass = "Glass", bubble_column = "Bubble Column",
  frogspawn = "Frogspawn", hanging_roots = "Hanging Roots", redstone_block = "Block of Redstone",
  deepslate_coal_ore = "Deepslate Coal Ore", sea_pickle = "Sea Pickle",
  dead_bubble_coral_block = "Dead Bubble Coral Block",
  yellow_concrete = "Yellow Concrete", acacia_log = "Acacia Log", cyan_stained_glass = "Cyan Stained Glass",
  infested_cobblestone = "Infested Cobblestone", crimson_fence = "Crimson Fence", smooth_quartz = "Smooth Quartz Block",
  exposed_cut_copper = "Exposed Cut Copper", gold_ore = "Gold Ore", black_terracotta = "Black Terracotta",
  bamboo_mosaic_slab = "Bamboo Mosaic Slab", redstone_wire = "Redstone Wire", lightning_rod = "Lightning Rod",
  copper_block = "Block of Copper", dark_oak_sapling = "Dark Oak Sapling", brown_candle_cake = "Cake with Brown Candle",
  black_bed = "Black Bed", sunflower = "Sunflower", dark_oak_door = "Dark Oak Door",
  spruce_wall_hanging_sign = "Spruce Wall Hanging Sign", magenta_candle = "Magenta Candle",
  light_blue_glazed_terracotta = "Light Blue Glazed Terracotta", end_gateway = "End Gateway", coal_ore = "Coal Ore",
  bamboo_block = "Block of Bamboo", lime_banner = "Lime Banner", potted_warped_roots = "Potted Warped Roots",
  damaged_anvil = "Damaged Anvil", potted_fern = "Potted Fern", powered_rail = "Powered Rail",
  smooth_sandstone_stairs = "Smooth Sandstone Stairs", infested_mossy_stone_bricks = "Infested Mossy Stone Bricks",
  purpur_slab = "Purpur Slab", gray_bed = "Gray Bed", jack_o_lantern = "Jack o'Lantern",
  magenta_terracotta = "Magenta Terracotta", birch_hanging_sign = "Birch Hanging Sign",
  horn_coral_wall_fan = "Horn Coral Wall Fan", tube_coral_fan = "Tube Coral Fan", flower_pot = "Flower Pot",
  diamond_ore = "Diamond Ore", jigsaw = "Jigsaw Block", infested_stone_bricks = "Infested Stone Bricks",
  big_dripleaf_stem = "Big Dripleaf Stem", infested_cracked_stone_bricks = "Infested Cracked Stone Bricks",
  lime_wool = "Lime Wool", polished_diorite_slab = "Polished Diorite Slab", green_candle = "Green Candle",
  polished_deepslate = "Polished Deepslate", cobbled_deepslate = "Cobbled Deepslate", bricks = "Bricks",
  birch_sapling = "Birch Sapling", orange_stained_glass_pane = "Orange Stained Glass Pane", blue_carpet = "Blue Carpet",
  player_head = "Player Head", rose_bush = "Rose Bush", brain_coral_wall_fan = "Brain Coral Wall Fan",
  purple_concrete = "Purple Concrete", moss_block = "Moss Block", dead_fire_coral_fan = "Dead Fire Coral Fan",
  jungle_hanging_sign = "Jungle Hanging Sign", green_terracotta = "Green Terracotta", red_sandstone = "Red Sandstone",
  yellow_bed = "Yellow Bed", piston = "Piston", andesite_wall = "Andesite Wall", black_banner = "Black Banner",
  acacia_door = "Acacia Door", jungle_pressure_plate = "Jungle Pressure Plate",
  dark_prismarine_stairs = "Dark Prismarine Stairs", acacia_leaves = "Acacia Leaves", andesite_stairs = "Andesite Stairs",
  birch_log = "Birch Log", jungle_sign = "Jungle Sign", composter = "Composter", red_candle_cake = "Cake with Red Candle",
  weeping_vines = "Weeping Vines", polished_blackstone_brick_stairs = "Polished Blackstone Brick Stairs",
  gray_stained_glass = "Gray Stained Glass", spruce_stairs = "Spruce Stairs", bamboo_sapling = "Bamboo Shoot",
  blue_orchid = "Blue Orchid", mossy_stone_brick_wall = "Mossy Stone Brick Wall", acacia_wood = "Acacia Wood",
  rail = "Rail", black_shulker_box = "Black Shulker Box", stripped_acacia_wood = "Stripped Acacia Wood", mud = "Mud",
  chiseled_red_sandstone = "Chiseled Red Sandstone", pumpkin_stem = "Pumpkin Stem", bamboo = "Bamboo",
  fire_coral_block = "Fire Coral Block", cracked_nether_bricks = "Cracked Nether Bricks", oak_log = "Oak Log",
  netherrack = "Netherrack", sugar_cane = "Sugar Cane", crimson_planks = "Crimson Planks",
  warped_nylium = "Warped Nylium",
  oak_hanging_sign = "Oak Hanging Sign", pink_stained_glass_pane = "Pink Stained Glass Pane",
  cyan_terracotta = "Cyan Terracotta", void_air = "Void Air", attached_melon_stem = "Attached Melon Stem",
  purpur_stairs = "Purpur Stairs", large_amethyst_bud = "Large Amethyst Bud",
  cracked_stone_bricks = "Cracked Stone Bricks",
  light_gray_shulker_box = "Light Gray Shulker Box", warped_fence = "Warped Fence", beacon = "Beacon",
  dead_horn_coral_wall_fan = "Dead Horn Coral Wall Fan", mud_brick_stairs = "Mud Brick Stairs",
  potted_pink_tulip = "Potted Pink Tulip", stripped_warped_stem = "Stripped Warped Stem",
  yellow_stained_glass_pane = "Yellow Stained Glass Pane", lime_candle_cake = "Cake with Lime Candle",
  acacia_planks = "Acacia Planks", diorite_slab = "Diorite Slab", mangrove_slab = "Mangrove Slab",
  white_wool = "White Wool", lectern = "Lectern", chorus_plant = "Chorus Plant", light_blue_bed = "Light Blue Bed",
  cobblestone_slab = "Cobblestone Slab", hay_block = "Hay Bale", wither_rose = "Wither Rose", tall_grass = "Tall Grass",
  blackstone_stairs = "Blackstone Stairs", black_concrete_powder = "Black Concrete Powder",
  water_cauldron = "Water Cauldron", piglin_wall_head = "Piglin Wall Head", warped_button = "Warped Button",
  light_blue_shulker_box = "Light Blue Shulker Box", bubble_coral_block = "Bubble Coral Block", large_fern = "Large Fern",
  jukebox = "Jukebox", white_banner = "White Banner", wet_sponge = "Wet Sponge",
  light_blue_concrete_powder = "Light Blue Concrete Powder",
  waxed_weathered_cut_copper_stairs = "Waxed Weathered Cut Copper Stairs", magma_block = "Magma Block",
  dark_oak_pressure_plate = "Dark Oak Pressure Plate",
  waxed_exposed_cut_copper_stairs = "Waxed Exposed Cut Copper Stairs",
  blue_terracotta = "Blue Terracotta", light_blue_stained_glass = "Light Blue Stained Glass",
  brown_terracotta = "Brown Terracotta", stripped_mangrove_log = "Stripped Mangrove Log",
  end_stone_brick_slab = "End Stone Brick Slab", diamond_block = "Block of Diamond",
  light_blue_stained_glass_pane = "Light Blue Stained Glass Pane", deepslate_tile_stairs = "Deepslate Tile Stairs",
  turtle_egg = "Turtle Egg", dark_oak_wood = "Dark Oak Wood", gray_candle = "Gray Candle", warped_slab = "Warped Slab",
  spruce_button = "Spruce Button", magenta_candle_cake = "Cake with Magenta Candle", birch_fence = "Birch Fence",
  iron_bars = "Iron Bars", stone_brick_stairs = "Stone Brick Stairs", lime_stained_glass = "Lime Stained Glass",
  chiseled_sandstone = "Chiseled Sandstone", beehive = "Beehive", calcite = "Calcite",
  raw_iron_block = "Block of Raw Iron",
  light_blue_wool = "Light Blue Wool", brown_candle = "Brown Candle",
  waxed_oxidized_cut_copper_stairs = "Waxed Oxidized Cut Copper Stairs", light_gray_bed = "Light Gray Bed",
  end_rod = "End Rod", brown_stained_glass = "Brown Stained Glass", pink_bed = "Pink Bed",
  light_gray_candle = "Light Gray Candle", chain_command_block = "Chain Command Block",
  purple_terracotta = "Purple Terracotta", stripped_warped_hyphae = "Stripped Warped Hyphae", observer = "Observer",
  purple_shulker_box = "Purple Shulker Box", light_gray_carpet = "Light Gray Carpet", dragon_head = "Dragon Head",
  dirt = "Dirt", smooth_quartz_stairs = "Smooth Quartz Stairs", stone_bricks = "Stone Bricks",
  jungle_fence_gate = "Jungle Fence Gate", bamboo_planks = "Bamboo Planks",
  light_gray_concrete_powder = "Light Gray Concrete Powder",
  light_gray_stained_glass_pane = "Light Gray Stained Glass Pane", dark_oak_stairs = "Dark Oak Stairs",
  brewing_stand = "Brewing Stand", detector_rail = "Detector Rail", pink_concrete_powder = "Pink Concrete Powder",
  bamboo_pressure_plate = "Bamboo Pressure Plate", weeping_vines_plant = "Weeping Vines Plant",
  mangrove_pressure_plate = "Mangrove Pressure Plate", dead_tube_coral_wall_fan = "Dead Tube Coral Wall Fan",
  spore_blossom = "Spore Blossom", azalea = "Azalea", chain = "Chain", green_concrete = "Green Concrete",
  furnace = "Furnace", stripped_crimson_stem = "Stripped Crimson Stem", brick_wall = "Brick Wall",
  white_bed = "White Bed",
  bamboo_slab = "Bamboo Slab", carved_pumpkin = "Carved Pumpkin", cracked_deepslate_bricks = "Cracked Deepslate Bricks",
  sticky_piston = "Sticky Piston", bamboo_mosaic_stairs = "Bamboo Mosaic Stairs", red_terracotta = "Red Terracotta",
  magenta_glazed_terracotta = "Magenta Glazed Terracotta", cyan_bed = "Cyan Bed", prismarine_bricks = "Prismarine Bricks",
  prismarine_brick_stairs = "Prismarine Brick Stairs", prismarine_brick_slab = "Prismarine Brick Slab",
  cyan_candle_cake = "Cake with Cyan Candle", bamboo_wall_sign = "Bamboo Wall Sign",
  reinforced_deepslate = "Reinforced Deepslate", stripped_crimson_hyphae = "Stripped Crimson Hyphae",
  packed_mud = "Packed Mud", dead_horn_coral = "Dead Horn Coral", lime_glazed_terracotta = "Lime Glazed Terracotta",
  lily_pad = "Lily Pad", small_dripleaf = "Small Dripleaf", dead_bubble_coral_wall_fan = "Dead Bubble Coral Wall Fan",
  potted_orange_tulip = "Potted Orange Tulip", bamboo_sign = "Bamboo Sign", powder_snow_cauldron = "Powder Snow Cauldron",
  cobweb = "Cobweb", kelp = "Kelp", amethyst_block = "Block of Amethyst", gray_concrete_powder = "Gray Concrete Powder",
  brown_carpet = "Brown Carpet", birch_planks = "Birch Planks", waxed_cut_copper = "Waxed Cut Copper",
  potted_wither_rose = "Potted Wither Rose", cave_air = "Cave Air", gray_banner = "Gray Banner",
  polished_blackstone_wall = "Polished Blackstone Wall", crimson_nylium = "Crimson Nylium",
  magenta_stained_glass = "Magenta Stained Glass", respawn_anchor = "Respawn Anchor", purpur_block = "Purpur Block",
  clay = "Clay", packed_ice = "Packed Ice", mangrove_stairs = "Mangrove Stairs", gold_block = "Block of Gold",
  ender_chest = "Ender Chest", light_blue_candle_cake = "Cake with Light Blue Candle",
  fire_coral_wall_fan = "Fire Coral Wall Fan", polished_granite_stairs = "Polished Granite Stairs",
  crimson_slab = "Crimson Slab", candle_cake = "Cake with Candle", granite = "Granite",
  twisting_vines_plant = "Twisting Vines Plant", dropper = "Dropper", potted_dark_oak_sapling = "Potted Dark Oak Sapling",
  potted_red_tulip = "Potted Red Tulip", bamboo_wall_hanging_sign = "Bamboo Wall Hanging Sign",
  stripped_spruce_log = "Stripped Spruce Log", cyan_stained_glass_pane = "Cyan Stained Glass Pane",
  wither_skeleton_skull = "Wither Skeleton Skull", brain_coral_block = "Brain Coral Block",
  cobbled_deepslate_stairs = "Cobbled Deepslate Stairs", air = "Air", magenta_banner = "Magenta Banner",
  waxed_weathered_cut_copper_slab = "Waxed Weathered Cut Copper Slab", granite_wall = "Granite Wall",
  jungle_planks = "Jungle Planks", mossy_stone_bricks = "Mossy Stone Bricks",
  end_stone_brick_stairs = "End Stone Brick Stairs", honeycomb_block = "Honeycomb Block", horn_coral = "Horn Coral",
  barrel = "Barrel", purple_carpet = "Purple Carpet", potted_warped_fungus = "Potted Warped Fungus", peony = "Peony",
  spruce_fence_gate = "Spruce Fence Gate", dead_brain_coral_block = "Dead Brain Coral Block", bookshelf = "Bookshelf",
  polished_basalt = "Polished Basalt", yellow_glazed_terracotta = "Yellow Glazed Terracotta", black_wool = "Black Wool",
  loom = "Loom", potted_dead_bush = "Potted Dead Bush", polished_blackstone_bricks = "Polished Blackstone Bricks",
  stripped_jungle_log = "Stripped Jungle Log", shroomlight = "Shroomlight", budding_amethyst = "Budding Amethyst",
  red_mushroom = "Red Mushroom", birch_leaves = "Birch Leaves", potted_dandelion = "Potted Dandelion",
  weathered_cut_copper_stairs = "Weathered Cut Copper Stairs", brown_concrete = "Brown Concrete",
  blue_stained_glass = "Blue Stained Glass", cyan_candle = "Cyan Candle", light_gray_terracotta = "Light Gray Terracotta",
  smooth_sandstone_slab = "Smooth Sandstone Slab", smooth_red_sandstone = "Smooth Red Sandstone",
  warped_door = "Warped Door", chiseled_stone_bricks = "Chiseled Stone Bricks", moss_carpet = "Moss Carpet",
  chiseled_bookshelf = "Chiseled Bookshelf", lever = "Lever", potted_crimson_fungus = "Potted Crimson Fungus",
  potted_cornflower = "Potted Cornflower", skeleton_skull = "Skeleton Skull",
  crimson_wall_hanging_sign = "Crimson Wall Hanging Sign", blue_wool = "Blue Wool",
  cracked_polished_blackstone_bricks = "Cracked Polished Blackstone Bricks", bamboo_mosaic = "Bamboo Mosaic",
  chorus_flower = "Chorus Flower", gravel = "Gravel", dead_tube_coral_block = "Dead Tube Coral Block",
  bamboo_trapdoor = "Bamboo Trapdoor", sand = "Sand", white_candle_cake = "Cake with White Candle",
  crimson_hyphae = "Crimson Hyphae", cut_red_sandstone = "Cut Red Sandstone", crying_obsidian = "Crying Obsidian",
  water = "Water", tube_coral = "Tube Coral", rooted_dirt = "Rooted Dirt", potted_azalea_bush = "Potted Azalea",
  red_concrete_powder = "Red Concrete Powder", deepslate = "Deepslate", light_blue_terracotta = "Light Blue Terracotta",
  deepslate_brick_stairs = "Deepslate Brick Stairs", sandstone_wall = "Sandstone Wall",
  black_candle_cake = "Cake with Black Candle", orange_glazed_terracotta = "Orange Glazed Terracotta",
  red_shulker_box = "Red Shulker Box", spruce_trapdoor = "Spruce Trapdoor",
  dead_fire_coral_block = "Dead Fire Coral Block",
  white_concrete = "White Concrete", magenta_shulker_box = "Magenta Shulker Box", netherite_block = "Block of Netherite",
  polished_granite_slab = "Polished Granite Slab", polished_diorite_stairs = "Polished Diorite Stairs",
  brown_stained_glass_pane = "Brown Stained Glass Pane", kelp_plant = "Kelp Plant", magenta_wool = "Magenta Wool",
  tall_seagrass = "Tall Seagrass", mangrove_fence_gate = "Mangrove Fence Gate", bubble_coral = "Bubble Coral",
  mangrove_log = "Mangrove Log", blue_bed = "Blue Bed", diorite = "Diorite", green_stained_glass = "Green Stained Glass",
  obsidian = "Obsidian", gray_concrete = "Gray Concrete", sandstone = "Sandstone", activator_rail = "Activator Rail",
  end_portal = "End Portal", green_banner = "Green Banner", glowstone = "Glowstone", lava = "Lava",
  dead_fire_coral_wall_fan = "Dead Fire Coral Wall Fan", white_stained_glass_pane = "White Stained Glass Pane",
  dark_oak_wall_sign = "Dark Oak Wall Sign", redstone_lamp = "Redstone Lamp", mangrove_roots = "Mangrove Roots",
  light_gray_candle_cake = "Cake with Light Gray Candle", stripped_spruce_wood = "Stripped Spruce Wood",
  orange_concrete_powder = "Orange Concrete Powder", green_bed = "Green Bed", cut_sandstone_slab = "Cut Sandstone Slab",
  birch_door = "Birch Door", wither_skeleton_wall_skull = "Wither Skeleton Wall Skull", potted_cactus = "Potted Cactus",
  brown_concrete_powder = "Brown Concrete Powder", light_gray_glazed_terracotta = "Light Gray Glazed Terracotta",
  cobbled_deepslate_slab = "Cobbled Deepslate Slab", pink_candle = "Pink Candle", white_tulip = "White Tulip",
  andesite_slab = "Andesite Slab", mangrove_wood = "Mangrove Wood", deepslate_gold_ore = "Deepslate Gold Ore",
  waxed_oxidized_cut_copper = "Waxed Oxidized Cut Copper", structure_block = "Structure Block",
  gray_glazed_terracotta = "Gray Glazed Terracotta", medium_amethyst_bud = "Medium Amethyst Bud", bedrock = "Bedrock",
  brown_mushroom_block = "Brown Mushroom Block", infested_deepslate = "Infested Deepslate", purple_wool = "Purple Wool",
  melon_stem = "Melon Stem", pink_wool = "Pink Wool", deepslate_emerald_ore = "Deepslate Emerald Ore",
  magenta_concrete_powder = "Magenta Concrete Powder", red_banner = "Red Banner", pink_tulip = "Pink Tulip",
  horn_coral_fan = "Horn Coral Fan", lime_concrete = "Lime Concrete", cornflower = "Cornflower",
  mossy_cobblestone = "Mossy Cobblestone", dark_prismarine_slab = "Dark Prismarine Slab", jungle_slab = "Jungle Slab",
  deepslate_brick_wall = "Deepslate Brick Wall", mangrove_wall_hanging_sign = "Mangrove Wall Hanging Sign",
  allium = "Allium", magenta_bed = "Magenta Bed", waxed_exposed_cut_copper = "Waxed Exposed Cut Copper",
  redstone_wall_torch = "Redstone Wall Torch", tnt = "TNT", mossy_cobblestone_stairs = "Mossy Cobblestone Stairs",
  potted_red_mushroom = "Potted Red Mushroom", mossy_stone_brick_slab = "Mossy Stone Brick Slab",
  acacia_sapling = "Acacia Sapling", end_stone_bricks = "End Stone Bricks", deepslate_tile_wall = "Deepslate Tile Wall",
  orange_candle_cake = "Cake with Orange Candle", mud_brick_wall = "Mud Brick Wall",
  spruce_wall_sign = "Spruce Wall Sign",
  lime_terracotta = "Lime Terracotta", white_carpet = "White Carpet", jungle_door = "Jungle Door",
  nether_brick_stairs = "Nether Brick Stairs", spruce_fence = "Spruce Fence", cactus = "Cactus",
  mushroom_stem = "Mushroom Stem", acacia_fence_gate = "Acacia Fence Gate", moving_piston = "Moving Piston",
  end_portal_frame = "End Portal Frame", dripstone_block = "Dripstone Block", chipped_anvil = "Chipped Anvil",
  oak_sign = "Oak Sign", weathered_copper = "Weathered Copper", acacia_stairs = "Acacia Stairs",
  mud_bricks = "Mud Bricks",
  spruce_wood = "Spruce Wood", potted_poppy = "Potted Poppy", crimson_pressure_plate = "Crimson Pressure Plate",
  oxeye_daisy = "Oxeye Daisy", pink_concrete = "Pink Concrete", emerald_ore = "Emerald Ore",
  red_nether_brick_stairs = "Red Nether Brick Stairs", podzol = "Podzol", jungle_trapdoor = "Jungle Trapdoor",
  dark_oak_fence_gate = "Dark Oak Fence Gate", sculk_sensor = "Sculk Sensor", nether_gold_ore = "Nether Gold Ore",
  crimson_button = "Crimson Button", stripped_dark_oak_wood = "Stripped Dark Oak Wood",
  gray_terracotta = "Gray Terracotta",
  light_blue_banner = "Light Blue Banner", structure_void = "Structure Void", light_gray_concrete = "Light Gray Concrete",
  glass_pane = "Glass Pane", blackstone = "Blackstone", black_candle = "Black Candle", warped_roots = "Warped Roots",
  nether_portal = "Nether Portal", dead_bubble_coral = "Dead Bubble Coral", cobblestone_wall = "Cobblestone Wall",
  tube_coral_wall_fan = "Tube Coral Wall Fan", stripped_bamboo_block = "Block of Stripped Bamboo",
  orange_tulip = "Orange Tulip", stripped_birch_wood = "Stripped Birch Wood", oak_trapdoor = "Oak Trapdoor",
  glow_lichen = "Glow Lichen", nether_sprouts = "Nether Sprouts", birch_fence_gate = "Birch Fence Gate",
  ochre_froglight = "Ochre Froglight", birch_sign = "Birch Sign", waxed_cut_copper_stairs = "Waxed Cut Copper Stairs",
  soul_fire = "Soul Fire", orange_terracotta = "Orange Terracotta", waxed_copper_block = "Waxed Block of Copper",
  attached_pumpkin_stem = "Attached Pumpkin Stem", vine = "Vines", stone = "Stone", spruce_sign = "Spruce Sign",
  purple_candle = "Purple Candle", dark_oak_trapdoor = "Dark Oak Trapdoor", lantern = "Lantern",
  warped_stem = "Warped Stem", note_block = "Note Block", chiseled_nether_bricks = "Chiseled Nether Bricks",
  oak_button = "Oak Button", raw_gold_block = "Block of Raw Gold", oak_fence = "Oak Fence", oak_leaves = "Oak Leaves",
  dark_oak_leaves = "Dark Oak Leaves", brown_banner = "Brown Banner",
  weathered_cut_copper_slab = "Weathered Cut Copper Slab", stripped_mangrove_wood = "Stripped Mangrove Wood",
  mangrove_trapdoor = "Mangrove Trapdoor", muddy_mangrove_roots = "Muddy Mangrove Roots",
  polished_blackstone_brick_slab = "Polished Blackstone Brick Slab", orange_bed = "Orange Bed",
  orange_banner = "Orange Banner", deepslate_tile_slab = "Deepslate Tile Slab", barrier = "Barrier",
  acacia_hanging_sign = "Acacia Hanging Sign", emerald_block = "Block of Emerald", crimson_sign = "Crimson Sign",
  zombie_wall_head = "Zombie Wall Head", waxed_weathered_cut_copper = "Waxed Weathered Cut Copper",
  diorite_stairs = "Diorite Stairs", pink_carpet = "Pink Carpet", warped_sign = "Warped Sign",
  tinted_glass = "Tinted Glass", purpur_pillar = "Purpur Pillar", azalea_leaves = "Azalea Leaves",
  green_candle_cake = "Cake with Green Candle", dead_brain_coral_wall_fan = "Dead Brain Coral Wall Fan", light = "Light",
  acacia_sign = "Acacia Sign", orange_shulker_box = "Orange Shulker Box", dried_kelp_block = "Dried Kelp Block",
  potatoes = "Potatoes", crimson_stairs = "Crimson Stairs", blue_shulker_box = "Blue Shulker Box", target = "Target",
  yellow_candle = "Yellow Candle", orange_wool = "Orange Wool", stripped_birch_log = "Stripped Birch Log",
  dirt_path = "Dirt Path", crimson_trapdoor = "Crimson Trapdoor", waxed_weathered_copper = "Waxed Weathered Copper",
  dark_oak_hanging_sign = "Dark Oak Hanging Sign", dark_oak_sign = "Dark Oak Sign", oak_wall_sign = "Oak Wall Sign",
  oxidized_cut_copper_stairs = "Oxidized Cut Copper Stairs", orange_candle = "Orange Candle",
  polished_andesite_stairs = "Polished Andesite Stairs", pearlescent_froglight = "Pearlescent Froglight",
  polished_blackstone_stairs = "Polished Blackstone Stairs", piglin_head = "Piglin Head",
  cyan_concrete_powder = "Cyan Concrete Powder", blue_candle_cake = "Cake with Blue Candle", cocoa = "Cocoa",
  sea_lantern = "Sea Lantern", warped_trapdoor = "Warped Trapdoor", blackstone_wall = "Blackstone Wall",
  creeper_wall_head = "Creeper Wall Head", bamboo_fence = "Bamboo Fence", pink_shulker_box = "Pink Shulker Box",
  red_wool = "Red Wool", polished_granite = "Polished Granite",
  heavy_weighted_pressure_plate = "Heavy Weighted Pressure Plate", warped_wall_hanging_sign = "Warped Wall Hanging Sign",
  red_nether_brick_slab = "Red Nether Brick Slab", player_wall_head = "Player Wall Head",
  pink_stained_glass = "Pink Stained Glass", potted_flowering_azalea_bush = "Potted Flowering Azalea",
  mangrove_wall_sign = "Mangrove Wall Sign", white_concrete_powder = "White Concrete Powder",
  spruce_sapling = "Spruce Sapling", blackstone_slab = "Blackstone Slab",
  birch_wall_hanging_sign = "Birch Wall Hanging Sign", polished_blackstone_brick_wall = "Polished Blackstone Brick Wall",
  nether_bricks = "Nether Bricks", bamboo_button = "Bamboo Button", potted_spruce_sapling = "Potted Spruce Sapling",
  polished_deepslate_wall = "Polished Deepslate Wall", smooth_quartz_slab = "Smooth Quartz Slab",
  oak_wall_hanging_sign = "Oak Wall Hanging Sign", yellow_candle_cake = "Cake with Yellow Candle",
  shulker_box = "Shulker Box", cut_copper_slab = "Cut Copper Slab", dead_tube_coral = "Dead Tube Coral",
  twisting_vines = "Twisting Vines", flowering_azalea_leaves = "Flowering Azalea Leaves", purple_bed = "Purple Bed",
  potted_azure_bluet = "Potted Azure Bluet", andesite = "Andesite", potted_birch_sapling = "Potted Birch Sapling",
  polished_andesite_slab = "Polished Andesite Slab", acacia_fence = "Acacia Fence", yellow_wool = "Yellow Wool",
  smooth_red_sandstone_stairs = "Smooth Red Sandstone Stairs", amethyst_cluster = "Amethyst Cluster",
  cyan_shulker_box = "Cyan Shulker Box", cyan_carpet = "Cyan Carpet", oak_wood = "Oak Wood",
  sandstone_slab = "Sandstone Slab", brick_stairs = "Brick Stairs", potted_bamboo = "Potted Bamboo",
  powder_snow = "Powder Snow", purple_stained_glass = "Purple Stained Glass", smooth_basalt = "Smooth Basalt",
  potted_oak_sapling = "Potted Oak Sapling", bamboo_hanging_sign = "Bamboo Hanging Sign",
  yellow_stained_glass = "Yellow Stained Glass", dead_horn_coral_fan = "Dead Horn Coral Fan",
  polished_deepslate_stairs = "Polished Deepslate Stairs", slime_block = "Slime Block",
  potted_white_tulip = "Potted White Tulip", poppy = "Poppy", potted_acacia_sapling = "Potted Acacia Sapling",
  jungle_wood = "Jungle Wood", dark_oak_planks = "Dark Oak Planks", bubble_coral_wall_fan = "Bubble Coral Wall Fan",
  warped_hyphae = "Warped Hyphae", prismarine = "Prismarine", terracotta = "Terracotta",
  dead_bubble_coral_fan = "Dead Bubble Coral Fan", iron_door = "Iron Door", yellow_shulker_box = "Yellow Shulker Box",
  prismarine_slab = "Prismarine Slab", waxed_cut_copper_slab = "Waxed Cut Copper Slab", acacia_slab = "Acacia Slab",
  birch_slab = "Birch Slab", white_shulker_box = "White Shulker Box", magenta_concrete = "Magenta Concrete",
  big_dripleaf = "Big Dripleaf", orange_stained_glass = "Orange Stained Glass",
  purple_candle_cake = "Cake with Purple Candle", crimson_fence_gate = "Crimson Fence Gate",
  sculk_catalyst = "Sculk Catalyst", anvil = "Anvil", purple_concrete_powder = "Purple Concrete Powder",
  lodestone = "Lodestone", exposed_cut_copper_slab = "Exposed Cut Copper Slab",
  dark_oak_wall_hanging_sign = "Dark Oak Wall Hanging Sign", crimson_door = "Crimson Door", melon = "Melon",
  jungle_button = "Jungle Button", waxed_oxidized_cut_copper_slab = "Waxed Oxidized Cut Copper Slab",
  jungle_log = "Jungle Log", chest = "Chest", blue_glazed_terracotta = "Blue Glazed Terracotta", red_bed = "Red Bed",
  chiseled_deepslate = "Chiseled Deepslate", creeper_head = "Creeper Head", coarse_dirt = "Coarse Dirt",
  tripwire_hook = "Tripwire Hook", fern = "Fern", potted_allium = "Potted Allium", conduit = "Conduit",
  purple_glazed_terracotta = "Purple Glazed Terracotta", petrified_oak_slab = "Petrified Oak Slab",
  horn_coral_block = "Horn Coral Block", small_amethyst_bud = "Small Amethyst Bud", birch_button = "Birch Button",
  brain_coral_fan = "Brain Coral Fan", spawner = "Monster Spawner",
  potted_lily_of_the_valley = "Potted Lily of the Valley",
  oak_stairs = "Oak Stairs", red_mushroom_block = "Red Mushroom Block", skeleton_wall_skull = "Skeleton Wall Skull",
  smooth_sandstone = "Smooth Sandstone", scaffolding = "Scaffolding", warped_fungus = "Warped Fungus",
  quartz_pillar = "Quartz Pillar", stripped_acacia_log = "Stripped Acacia Log", light_blue_carpet = "Light Blue Carpet",
  birch_stairs = "Birch Stairs", bamboo_door = "Bamboo Door", cobblestone_stairs = "Cobblestone Stairs",
  red_nether_bricks = "Red Nether Bricks", potted_jungle_sapling = "Potted Jungle Sapling", oak_planks = "Oak Planks",
  dark_oak_fence = "Dark Oak Fence", stone_slab = "Stone Slab", brown_shulker_box = "Brown Shulker Box",
  polished_blackstone_button = "Polished Blackstone Button", red_tulip = "Red Tulip", lime_carpet = "Lime Carpet",
  lapis_block = "Block of Lapis Lazuli", oak_slab = "Oak Slab", light_blue_candle = "Light Blue Candle",
  fletching_table = "Fletching Table", red_concrete = "Red Concrete", dragon_wall_head = "Dragon Wall Head",
  purple_banner = "Purple Banner", waxed_exposed_copper = "Waxed Exposed Copper", jungle_wall_sign = "Jungle Wall Sign",
  stripped_jungle_wood = "Stripped Jungle Wood", dead_brain_coral_fan = "Dead Brain Coral Fan",
  oxidized_cut_copper_slab = "Oxidized Cut Copper Slab", sponge = "Sponge", polished_diorite = "Polished Diorite",
  coal_block = "Block of Coal", brown_wool = "Brown Wool", red_sand = "Red Sand", white_terracotta = "White Terracotta",
  prismarine_stairs = "Prismarine Stairs", nether_brick_wall = "Nether Brick Wall",
  red_sandstone_stairs = "Red Sandstone Stairs", bubble_coral_fan = "Bubble Coral Fan",
  cracked_deepslate_tiles = "Cracked Deepslate Tiles", stripped_oak_log = "Stripped Oak Log",
  warped_hanging_sign = "Warped Hanging Sign", purple_stained_glass_pane = "Purple Stained Glass Pane",
  spruce_log = "Spruce Log", warped_planks = "Warped Planks", red_stained_glass_pane = "Red Stained Glass Pane",
  brown_bed = "Brown Bed", command_block = "Command Block", crafting_table = "Crafting Table",
  acacia_wall_sign = "Acacia Wall Sign", redstone_torch = "Redstone Torch", smooth_stone = "Smooth Stone",
  gray_wool = "Gray Wool", granite_stairs = "Granite Stairs", iron_trapdoor = "Iron Trapdoor",
  acacia_button = "Acacia Button", dark_prismarine = "Dark Prismarine", bone_block = "Bone Block", wheat = "Wheat Crops",
  red_carpet = "Red Carpet", enchanting_table = "Enchanting Table", orange_carpet = "Orange Carpet",
  stonecutter = "Stonecutter", tripwire = "Tripwire", yellow_terracotta = "Yellow Terracotta",
  yellow_concrete_powder = "Yellow Concrete Powder", lime_bed = "Lime Bed", birch_pressure_plate = "Birch Pressure Plate",
  potted_blue_orchid = "Potted Blue Orchid", blue_ice = "Blue Ice", warped_wart_block = "Warped Wart Block",
  redstone_ore = "Redstone Ore", light_gray_wool = "Light Gray Wool", acacia_trapdoor = "Acacia Trapdoor",
  lapis_ore = "Lapis Lazuli Ore", ancient_debris = "Ancient Debris", stone_brick_wall = "Stone Brick Wall",
  jungle_fence = "Jungle Fence", infested_chiseled_stone_bricks = "Infested Chiseled Stone Bricks",
  end_stone = "End Stone",
  basalt = "Basalt", oxidized_copper = "Oxidized Copper", trapped_chest = "Trapped Chest", smoker = "Smoker",
  quartz_slab = "Quartz Slab", smooth_red_sandstone_slab = "Smooth Red Sandstone Slab",
  white_stained_glass = "White Stained Glass", green_shulker_box = "Green Shulker Box", cyan_concrete = "Cyan Concrete",
  pink_banner = "Pink Banner", mangrove_sign = "Mangrove Sign", tuff = "Tuff",
  crimson_hanging_sign = "Crimson Hanging Sign", blue_stained_glass_pane = "Blue Stained Glass Pane",
  nether_quartz_ore = "Nether Quartz Ore", zombie_head = "Zombie Head", warped_pressure_plate = "Warped Pressure Plate",
  mycelium = "Mycelium", stone_button = "Stone Button", piston_head = "Piston Head",
  brown_glazed_terracotta = "Brown Glazed Terracotta", magenta_carpet = "Magenta Carpet", carrots = "Carrots",
  black_glazed_terracotta = "Black Glazed Terracotta", stripped_dark_oak_log = "Stripped Dark Oak Log",
  spruce_door = "Spruce Door", pointed_dripstone = "Pointed Dripstone", fire_coral = "Fire Coral",
  red_sandstone_slab = "Red Sandstone Slab", cut_copper = "Cut Copper", }
